### PR TITLE
OscTrackingData refactor

### PR DESCRIPTION
**Pull request by yangwill**
Refactors `osc_tracking_data` into separate files for readability and merges in the rest of Yu-Ming's walking controller improvements.

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/263)

### CODE REVIEW

**Review by Brian-Acosta — COMMENTED** [review]
A few minor comments but LGTM. Still debugging the standing controller on my end too - currently updating to the most recent drake version. Will approve once we figure this out

**Review by yminchen — CHANGES_REQUESTED** [review]
Added a few comments after reading the class for the second time.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/263#-:-MlV7g_uBrCk674ReIxc:bw009pm)* status: all files reviewed, 21 unresolved discussions (waiting on @yangwill)

___
*[systems/controllers/osc/options_tracking_data.h, line 55 at r4](https://reviewable.io/reviews/dairlab/dairlib/263#-MlV66HF2wQcmOi66wOp:-MlV66HF2wQcmOi66wOq:b-zia6ly) ([raw file](https://github.com/dairlab/dairlib/blob/4b93b1172dbd5820a41ed772a6692a86050338d1/systems/controllers/osc/options_tracking_data.h#L55)):*
> ```objc
> 
>  private:
>   void UpdateYError() override;
> ```

Can we replace `override` with `final` wherever suitable? (probably for`UpdateYError`, `UpdateYdotError` and `UpdateYddotCmd`)  It's easier to read and understand the whole `OscTrackingData` hierarchy in this way. 
___
*[systems/controllers/osc/options_tracking_data.cc, line 80 at r4](https://reviewable.io/reviews/dairlab/dairlib/263#-MlV3Mch3P2COCHr3gha:-MlV3Mch3P2COCHr3ghb:berg6op) ([raw file](https://github.com/dairlab/dairlib/blob/4b93b1172dbd5820a41ed772a6692a86050338d1/systems/controllers/osc/options_tracking_data.cc#L80)):*
> ```cpp
> }
> 
> void OptionsTrackingData::UpdateYddotDes(double t,
> ```

The derived class`RotTaskSpaceTrackingData` overrides this method. We should either copy the `idx_zero_feedforward_accel_` and `ff_accel_multiplier_` functionality to `RotTaskSpaceTrackingData` or warn the users that this features are not supported in `RotTaskSpaceTrackingData`  
___
*[systems/controllers/osc/options_tracking_data.cc, line 102 at r4](https://reviewable.io/reviews/dairlab/dairlib/263#-MlV2Dwd20VMA7VdXXJg:-MlV2Dwd20VMA7VdXXJh:b-pz3tdq) ([raw file](https://github.com/dairlab/dairlib/blob/4b93b1172dbd5820a41ed772a6692a86050338d1/systems/controllers/osc/options_tracking_data.cc#L102)):*
> ```cpp
>   }
> 
>   yddot_command_ = yddot_des_converted_ +
> ```

I just realized that the class assumes both the actual traj and the desired traj are viewed in world frame, so we also need to apply `view_frame_rot_T_` on `yddot_des_converted_`
___
*[systems/controllers/osc/relative_translation_tracking_data.cc, line 40 at r4](https://reviewable.io/reviews/dairlab/dairlib/263#-MlV49GT-xrPoFr_8klF:-MlV49GT-xrPoFr_8klG:b1kdwtl) ([raw file](https://github.com/dairlab/dairlib/blob/4b93b1172dbd5820a41ed772a6692a86050338d1/systems/controllers/osc/relative_translation_tracking_data.cc#L40)):*
> ```cpp
>     const drake::trajectories::Trajectory<double>& traj, double t,
>     double t_gait_cycle, const int fsm_state, const VectorXd& v_proj) {
>   to_frame_data_->Update(x_w_spr, context_w_spr, x_wo_spr, context_wo_spr, traj,
> ```

Currently we update everything for `to_frame_data_` and `from_frame_data_`, while we only need to call `UpdateActual` for them. Is there a way to do this? 
I did this in my branch with a flag, but I know flags in base class is what we want to avoid.

**Comment by yangwill** [comment]
Somehow commit `edcc5ae` broke the walking controller, still need to look into why.

**Review by Brian-Acosta — APPROVED** [review]
> Reviewed 12 of 13 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/263)* status: all files reviewed, 19 unresolved discussions (waiting on @yminchen)

**Review by Brian-Acosta — APPROVED** [review]
:lgtm: We can merge after hardware testing 

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/263#-:-Mlly0NTCOt8a3WTeik4:bbuisy1)* status: all files reviewed, 19 unresolved discussions (waiting on @yminchen)

**Pull request merged**
