### PR TITLE
Update to current Drake master.

### PR DESCRIPTION
**Pull request by mposa**
We're about 5 months behind on Drake master. This PR fixes deprecation issues that have arisen since then. While it compiles, it's probably a good idea to regression test any current projects to ensure no changes. This essentially updates Drake from v0.24.0 to v0.29.0 (though we are tracking master, not these releases).

I recommend reviewing these release notes to preview any relevant changes--there are some items in there that may be useful (OSQP, trajectory optimization, and dynamics updates in particular).

https://drake.mit.edu/release_notes/release_notes.html

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/243)

### CODE REVIEW

**Comment by yangwill** [comment]
Through basic testing, I don't see any immediate issues in my branches. Will wait for Yu Ming to make sure it doesn't break his work. Unless some issue pops up, LGTM.

**Review by yminchen — CHANGES_REQUESTED** [review]
It's working in my branch. 

@mposa I also merged `drake-upgrade` with `master` locally, so I can push the changes to this PR if you want. 

> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/243#-:-MZomndNApRZIHumwceb:b-vylmlg)* status: 1 of 29 files reviewed, 1 unresolved discussion (waiting on @mposa)

___
*[install/install_prereqs_ubuntu.sh, line 24 at r1](https://reviewable.io/reviews/dairlab/dairlib/243#-MZofTCOERxofq7Lgw0B:-MZofTCOERxofq7Lgw0C:bpqup4s) ([raw file](https://github.com/dairlab/dairlib/blob/e861cce6d404de40e8c9554c39d98f0d6a05fadd/install/install_prereqs_ubuntu.sh#L24)):*
> ```Shell
> touch install_prereqs_user_environment.sh
> wget "https://raw.githubusercontent.com/RobotLocomotion/drake/${DRAKE_COMMIT}/setup/ubuntu/source_distribution/packages-${ubuntu_codename}.txt"
> wget "https://raw.githubusercontent.com/RobotLocomotion/drake/${DRAKE_COMMIT}/setup/ubuntu/source_distribution/packages-${ubuntu_codename}-test-only.txt"
> ```

Is this a test code added by accident?

**Comment by mposa** [comment]
Please. Feel free to push here and merge once checks pass.

**Review by yminchen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/243#-:-MZoqGHBD5VRMzb7fyN9:bnfp4nl)* status: 1 of 29 files reviewed, 1 unresolved discussion (waiting on @mposa)

___
*[install/install_prereqs_ubuntu.sh, line 24 at r1](https://reviewable.io/reviews/dairlab/dairlib/243#-MZofTCOERxofq7Lgw0B:-MZoqBaeCll5yy0apGdO:b-h3g9co) ([raw file](https://github.com/dairlab/dairlib/blob/e861cce6d404de40e8c9554c39d98f0d6a05fadd/install/install_prereqs_ubuntu.sh#L24)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Is this a test code added by accident?
</blockquote></details>

Answered via Slack -- this line is needed for bazel test.

**Pull request merged**
