### PR TITLE
Updating the regularization costs methods and how we log them

### PR DESCRIPTION
**Pull request by yangwill**
Updating `lcmt_osc_output.lcm` so that we support any number of regularization costs. This changes the lcmtype so will break loading in old logs.

Also I changed the functions that set the regularization cost weights to be more consistent.

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/284)

### CODE REVIEW

**Comment by yminchen** [comment]
I agree with Brian. We should probably have backward compatibility. The rest of the codes look good to me

**Review by yangwill — COMMENTED** [review]
I made the plotting script backward compatible, but you still need to compile the old lcm message to use it.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/284#-:-MzWnDRv-cAK8go5U3kz:btfin03)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @Brian-Acosta, @yangwill, and @yminchen)

___
*[bindings/pydairlib/analysis/mbp_plotting_utils.py, line 345 at r1](https://reviewable.io/reviews/dairlab/dairlib/284#-Mxjo14HEev9PdNM-zP7:-MzWdSlhEB-bKY3-MLSf:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/5a9e88bbf373b16fe417d3192e30b09a19a06199/bindings/pydairlib/analysis/mbp_plotting_utils.py#L345)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Remove debugging break
</blockquote></details>

Done.
___
*[systems/controllers/osc/operational_space_control.h, line 141 at r1](https://reviewable.io/reviews/dairlab/dairlib/284#-Mxjoyrm0BuGbKtrKBld:-MzWdiuM6M90UV3gYD4S:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/5a9e88bbf373b16fe417d3192e30b09a19a06199/systems/controllers/osc/operational_space_control.h#L141)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Would be nice to still know that this is contact related from the function name. Maybe `SetContactRelaxationWeight` or `SetContactSoftConstraintWeight`
</blockquote></details>

Done.

**Review by yangwill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/284)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[bindings/pydairlib/analysis/mbp_plotting_utils.py, line 115 at r1](https://reviewable.io/reviews/dairlab/dairlib/284#-MxjnrBt9JnhlTvclMfu:-MzWnPALClNW4OX_kvsb:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/5a9e88bbf373b16fe417d3192e30b09a19a06199/bindings/pydairlib/analysis/mbp_plotting_utils.py#L115)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

We should provide some sort of backward compatibility. A good way would probably be to construct this object from existing costs using the hardcoded cost names
</blockquote></details>

Done.

**Review by Brian-Acosta — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yminchen)

**Review by Brian-Acosta — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/284#-:-N3vbFeoDT2m_VuFgB1-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yminchen)

**Comment by Brian-Acosta** [comment]
Approved - waiting on @yangwill to resolve conflicts

**Review by yangwill — COMMENTED** [review]
Added an easier method for backward compatibility: single boolean flag in plot config called: `use_archived_lcmtypes`. Would be a good idea to re-review, especially naming convention. 

Tested with lcmlog-01 that Brian sent me, which uses the old `lcmt_osc_output` and 05_10_22/lcmlog-08 which uses the new `lcmt_osc_output`

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/284#-:-N3yz2ZQ6BptDfAOCbqs:b-84vy9x)* status: 1 of 19 files reviewed, all discussions resolved (waiting on @Brian-Acosta and @yminchen)

**Pull request merged**
