### PR TITLE
Fixes for recent Drake deprecations

### PR DESCRIPTION
**Pull request by mposa**
Fixes errors and deprecation warnings due to upstream Drake changes

- API changes for some of the autodiff utilities
- Change to how YAML files are loaded

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)

### CODE REVIEW

**Comment by mposa** [comment]
Upstream changes [Drake](https://github.com/RobotLocomotion/drake/pull/16035) changed the ordering of MultibodyPlant joints, which have caught a number of places in our code where we make assumptions on the ordering, or where we log the state vector without names. 

Before this PR is merged, we need to be confident that these have been caught. So far, commits only touch places where unit tests caught failures @yminchen has already caught one (unfixed) example: https://github.com/DAIRLab/dairlib/blob/master/examples/Cassie/run_dircon_walking.cc#L118

**Review by Brian-Acosta — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1, 1 of 1 files at r2, 15 of 18 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: 32 of 37 files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta and @mposa)

___
*[bindings/pydairlib/lcm/lcm_trajectory_py.cc, line 52 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRWBCu7QAAeiUG_4V9:-MuRWBCu7QAAeiUG_4VA:b-wv7mma) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/bindings/pydairlib/lcm/lcm_trajectory_py.cc#L52)):*
> ```cpp
>            py::arg("trajectory_name"));
>   py::class_<DirconTrajectory>(m, "DirconTrajectory")
>       .def(py::init<const drake::multibody::MultibodyPlant<double>&, const std::string&>())      .def("WriteToFile", &LcmTrajectory::WriteToFile,
> ```

WriteToFile should be on the next line, probably just a typo
___
*[examples/Cassie/multibody_sim_w_platform.cc, line 89 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRWmlZ5jeE_EHdTlSE:-MuRWmlZ5jeE_EHdTlSF:b-om6kf9) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/multibody_sim_w_platform.cc#L89)):*
> ```cpp
>   }
> 
>   std::string urdf;
> ```

Very nitpicky but can we make this a ternary statement? e.g. 



_Code snippet:_
```cpp
std::string urdf = FLAGS_spring_model ? "examples/Cassie/urdf/cassie_v2.urdf" : 
                                        "examples/Cassie/urdf/cassie_fixed_springs.urdf";
```
___
*[examples/Cassie/visualize_trajectory.cc, line 70 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuR_7C2BrNmgGAnmXfi:-MuR_7C2BrNmgGAnmXfj:b-lypchl) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/visualize_trajectory.cc#L70)):*
> ```cpp
>         saved_traj.ReconstructMirrorStateTrajectory(optimal_traj.end_time());
>     VectorXd x_offset = VectorXd::Zero(nx);
>     x_offset(4) = optimal_traj.value(optimal_traj.end_time())(4) -
> ```

Probably shouldn't hard code this state index even though it's part of the floating base
___
*[examples/Cassie/test/cassie_state_estimator_test.cc, line 109 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuR_vjz92T4muIcL_ai:-MuR_vk-5Yr6ep9SY7CB:bxp4ull) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/test/cassie_state_estimator_test.cc#L109)):*
> ```cpp
>   // Example position (floating base position doesn't affect the result)
>   VectorXd q_init(plant_.num_positions());
>   q_init << 1, VectorXd::Zero(6), -0.084017,  -0.00120735, 0.366012, -0.6305,
> ```

Probably shouldn't hardcode this joint order (unless we want to have a test which fails if the joint ordering changes again, which could be valid)
___
*[lcm/dircon_saved_trajectory.h, line 142 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRb0la335rDZYq5wwl:-MuRb0la335rDZYq5wwm:b-481dpd) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/lcm/dircon_saved_trajectory.h#L142)):*
> ```objc
> 
>   // convenience map
>   // NOTE:
> ```

What is the NOTE ?
___
*[lcm/dircon_saved_trajectory.cc, line 469 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbL6r22ixDPc91e8E:-MuRbL6r22ixDPc91e8F:b-j4cewk) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/lcm/dircon_saved_trajectory.cc#L469)):*
> ```cpp
>       vel_map_[state_name] = i;
>     } else {
>       std::cerr << "Trajectory contains state names that are present in the "
> ```

should this say "are not present"?
___
*[lcm/dircon_saved_trajectory.cc, line 484 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbPHK7tR0LrLgFzjG:-MuRbPHLA4zw5wNq7XJP:b-7ropln) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/lcm/dircon_saved_trajectory.cc#L484)):*
> ```cpp
>       act_map_[motor_name] = i;
>     } else {
>       std::cerr << "Trajectory contains state names that are present in the "
> ```

ditto
___
*[solvers/nonlinear_constraint.cc, line 93 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbbi37af_Q9rj_iDC:-MuRbbi37af_Q9rj_iDD:besgyfe) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/solvers/nonlinear_constraint.cc#L93)):*
> ```cpp
>   } else {
>     *y = drake::math::InitializeAutoDiff(y0,
>                                                             dy * original_grad);
> ```

Formatting

**Review by yangwill — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 4 of 18 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: all files reviewed, 12 unresolved discussions (waiting on @mposa)

___
*[bindings/pydairlib/analysis/process_lcm_log.py, line 35 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRb8ka83XaBwp62LMP:-MuRb8ka83XaBwp62LMQ:b-dhio2k) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/bindings/pydairlib/analysis/process_lcm_log.py#L35)):*
> ```Python
>             channels[event.channel] = 0
>         else:
>             channels[event.channel] = channels[event.channel] + 1
> ```

maybe rename `channels` to `msgs_in_channel' for better readability
___
*[bindings/pydairlib/analysis/process_lcm_log.py, line 40 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbi3d4t8EpHP2-ysv:-MuRbi3d4t8EpHP2-ysw:btvgtwl) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/bindings/pydairlib/analysis/process_lcm_log.py#L40)):*
> ```Python
> 
> def print_log_summary(filename, log):
>     print(f"Channels in{filename}:\n")
> ```

nit, space between in and {filename}
___
*[examples/Cassie/run_dircon_walking.cc, line 418 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRfxMR6un7DGwAjzt6:-MuRfxMR6un7DGwAjzt7:b-3ul8la) ([raw file](https://github.com/dairlab/dairlib/blob/b5ed602fffc72653dba51395c7da256a51ca18eb/examples/Cassie/run_dircon_walking.cc#L418)):*
> ```cpp
>       options_list[i].setImpConstraintScaling({3, 4, 5}, s / 300.0);
>       options_list[i].setImpConstraintScaling({6, 7}, s / 24.0);
>       options_list[i].setImpConstraintScaling({8, 9}, s / 6.0);
> ```

Need to check to make sure these new indices are correct
___
*[examples/Cassie/run_dircon_walking.cc, line 806 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRck202AcezRyiQhj4:-MuRck202AcezRyiQhj5:b-yp9a49) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/run_dircon_walking.cc#L806)):*
> ```cpp
>     trajopt->ScaleForceVariables(1, idx_list, 1000);
>     // impulse
>     trajopt->ScaleImpulseVariables(base_wx_idx, idx_list, 10);
> ```

`base_wx_idx` is not guaranteed to correspond to index 0 of the impulse variables. Unless I'm mistaken, the impulse variable ordering is defined by the user and should not be affected by Drake's reordering of the joints.

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: 36 of 37 files reviewed, 11 unresolved discussions (waiting on @mposa and @yangwill)

___
*[bindings/pydairlib/analysis/process_lcm_log.py, line 35 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRb8ka83XaBwp62LMP:-MuRiXBF8dNr5MTu6EzW:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/bindings/pydairlib/analysis/process_lcm_log.py#L35)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

maybe rename `channels` to `msgs_in_channel' for better readability
</blockquote></details>

Done
___
*[bindings/pydairlib/analysis/process_lcm_log.py, line 40 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbi3d4t8EpHP2-ysv:-MuRiYD78MEBhYnFfB70:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/bindings/pydairlib/analysis/process_lcm_log.py#L40)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

nit, space between in and {filename}
</blockquote></details>

Done

**Review by yangwill — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: all files reviewed, 10 unresolved discussions (waiting on @Brian-Acosta and @mposa)

___
*[bindings/pydairlib/lcm/lcm_trajectory_py.cc, line 52 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRWBCu7QAAeiUG_4V9:-MuRjLn88JJOhgkmG8Lt:b-7rl0jd) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/bindings/pydairlib/lcm/lcm_trajectory_py.cc#L52)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

WriteToFile should be on the next line, probably just a typo
</blockquote></details>

done.
___
*[examples/Cassie/multibody_sim_w_platform.cc, line 89 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRWmlZ5jeE_EHdTlSE:-MuRjUey76bxeM3fe_r1:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/multibody_sim_w_platform.cc#L89)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Very nitpicky but can we make this a ternary statement? e.g. 
</blockquote></details>

done
___
*[examples/Cassie/visualize_trajectory.cc, line 70 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuR_7C2BrNmgGAnmXfi:-MuRmXK3BK5SnQGvHjTo:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/visualize_trajectory.cc#L70)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Probably shouldn't hard code this state index even though it's part of the floating base
</blockquote></details>

done
___
*[lcm/dircon_saved_trajectory.h, line 142 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRb0la335rDZYq5wwl:-MuRnVQ6D5nyHK_qdd2p:b-gsoqxo) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/lcm/dircon_saved_trajectory.h#L142)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

What is the NOTE ?
</blockquote></details>

finished the note.
___
*[lcm/dircon_saved_trajectory.cc, line 469 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbL6r22ixDPc91e8E:-MuRncdt4sHbjV_06lG3:b-7ql1td) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/lcm/dircon_saved_trajectory.cc#L469)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

should this say "are not present"?
</blockquote></details>

fixed
___
*[lcm/dircon_saved_trajectory.cc, line 484 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbPHK7tR0LrLgFzjG:-MuRndLZ-TeQydcabaUM:b-7ql1td) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/lcm/dircon_saved_trajectory.cc#L484)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

fixed
___
*[solvers/nonlinear_constraint.cc, line 93 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRbbi37af_Q9rj_iDC:-MuRnjY903j462BL3waY:b-7ql1td) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/solvers/nonlinear_constraint.cc#L93)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Formatting
</blockquote></details>

fixed

**Review by Brian-Acosta — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: all files reviewed, 3 unresolved discussions (waiting on @mposa)

**Review by yminchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: 36 of 38 files reviewed, 3 unresolved discussions (waiting on @Brian-Acosta, @mposa, @yangwill, and @yminchen)

___
*[examples/Cassie/run_dircon_walking.cc, line 418 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRfxMR6un7DGwAjzt6:-MuW-ALW-z__6C6A0yr3:b-viq5yi) ([raw file](https://github.com/dairlab/dairlib/blob/b5ed602fffc72653dba51395c7da256a51ca18eb/examples/Cassie/run_dircon_walking.cc#L418)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Need to check to make sure these new indices are correct
</blockquote></details>

Just checked. They should be correct because they are not dependent on the actually value of the indices anymore.
___
*[examples/Cassie/run_dircon_walking.cc, line 806 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuRck202AcezRyiQhj4:-MuW-Rpi7VBYwBI2DHWZ:b7wzf4t) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/run_dircon_walking.cc#L806)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

`base_wx_idx` is not guaranteed to correspond to index 0 of the impulse variables. Unless I'm mistaken, the impulse variable ordering is defined by the user and should not be affected by Drake's reordering of the joints.
</blockquote></details>

Good catch! I miscoded this one.

**Review by Brian-Acosta — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: all files reviewed, 3 unresolved discussions (waiting on @mposa and @yangwill)

**Review by Brian-Acosta — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274#-:-MuWtL119K2x49oJm6jr:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mposa and @yangwill)

**Review by mposa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274)* status: all files reviewed, 3 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[examples/Cassie/test/cassie_state_estimator_test.cc, line 109 at r5](https://reviewable.io/reviews/dairlab/dairlib/274#-MuR_vjz92T4muIcL_ai:-MuaywU62bYapbf1gJRT:b-17jqge) ([raw file](https://github.com/dairlab/dairlib/blob/8362f7eda54663bcbbbd80819b2bc7ecc3416957/examples/Cassie/test/cassie_state_estimator_test.cc#L109)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Probably shouldn't hardcode this joint order (unless we want to have a test which fails if the joint ordering changes again, which could be valid)
</blockquote></details>

I think it's not a bad idea to have a unit test which will fail if ordering changes.

**Review by yangwill — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/274#-:-Mul2edEALExkwVUoEvX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta)

**Pull request merged**
