### PR TITLE
Fix a bug in lipm_traj_gen

### PR DESCRIPTION
**Pull request by yminchen**
A little bug caught by `DRAKE_ASSERT()` when I run the code with valgirnd.

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/212)

### CODE REVIEW

**Comment by yangwill** [comment]
Can you give an explanation for what the bug is? Why don't the initializations for K and A not cause the same error?

**Comment by yminchen** [comment]
The number of polynomial segments should be equal to the number of columns of `alpha`. 
https://github.com/RobotLocomotion/drake/blob/master/common/trajectories/exponential_plus_piecewise_polynomial.h#L45
When running in debug mode, we get a runtime error from this line of code in the link.

This bug might cause issues, but it's still better to remove it to prevent potential memory leak.

**Comment by yangwill** [comment]
I'm just asking because I'm not convinced that this should be the source of the bug.

**Comment by yminchen** [comment]
Hmm maybe my statement was confusing. I probably shouldn't call this a "bug". 
I was debugging my code in a branch, but the program stopped early because of the `DRAKE_ASSERT()`. I had to make this one line fix to see valgrind outputing the message of the actual bug.

**Comment by yangwill** [comment]
Another option is to remove `K` `A` and `alpha` and just use the default constructor - ie `ExponentialPlusPiecewisePolynomial<double> exp;`. This fix seems cleaner to me than setting a value for alpha and not using it later.

**Comment by yminchen** [comment]
Yeah using default constructor is much cleaner!

**Review by yangwill — APPROVED** [review]
LGTM!

**Pull request merged**
