### PR TITLE
Minimal Changes to build on Jammy

### PR DESCRIPTION
**Pull request by Brian-Acosta**
Now that we have some new computers running Jammy, it's time to update dairlib accordingly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/351)

### CODE REVIEW

**Comment by Brian-Acosta** [comment]
This should probably be accompanied by adding the appropriate CI and officially purging any bionic support

**Review by mposa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/351)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @ebianchi)

___
*[`.bazelrc` line 55 at r2](https://reviewable.io/reviews/DAIRLab/dairlib/351#-NgHHUf89rnhpncLEpf9:-NgHHUf89rnhpncLEpfA:b-ebw48c) ([raw file](https://github.com/DAIRLab/dairlib/blob/9d7efbd389ba48a942453f13f6b6932cfd857233/.bazelrc#L55)):*
> ```
> 
> # build with snopt
> # TODO (@mposa) sync snopt version with Drake to build on Jammy
> ```

Can you explain this comment?  I don't have a machine running Jammy right now to test. Does the SNOPT file we have not work for jammy?

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/351)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @ebianchi and @mposa)

___
*[`.bazelrc` line 55 at r2](https://reviewable.io/reviews/DAIRLab/dairlib/351#-NgHHUf89rnhpncLEpf9:-NgJY2dE8hqsQ9Z1vxBw:b-bgx4lw) ([raw file](https://github.com/DAIRLab/dairlib/blob/9d7efbd389ba48a942453f13f6b6932cfd857233/.bazelrc#L55)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

Can you explain this comment?  I don't have a machine running Jammy right now to test. Does the SNOPT file we have not work for jammy?
</blockquote></details>

Still looking for the relevant slack message or PR for Drake to confirm, but my understanding is that the drake binaries build against SNOPT 7.4. 

Here's the compiler error we get on both jammy and macOS, when building either dairlib or drake with WITH_SNOPT=ON:



_Code snippet:_
```
external/snopt/src/sn70nobj.f:235:35:

  234 |             call dload ( nF, zero,    w, 1 )
      |                                      2
  235 |             call dload ( nF, zero, Elem, 1 )
      |                                   1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
```

**Review by mposa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/351)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @ebianchi)

___
*[`.bazelrc` line 55 at r2](https://reviewable.io/reviews/DAIRLab/dairlib/351#-NgHHUf89rnhpncLEpf9:-NgJhuNU7y-myFPs19CQ:b-fy74ej) ([raw file](https://github.com/DAIRLab/dairlib/blob/9d7efbd389ba48a942453f13f6b6932cfd857233/.bazelrc#L55)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Still looking for the relevant slack message or PR for Drake to confirm, but my understanding is that the drake binaries build against SNOPT 7.4. 

Here's the compiler error we get on both jammy and macOS, when building either dairlib or drake with WITH_SNOPT=ON:
</blockquote></details>

This is with SNOPT 7.4? I've been using 7.6, which is also what's linked via the dairlib README

https://www.seas.upenn.edu/~posa/snopt/snopt7.6.tar.gz

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/351)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @ebianchi and @mposa)

___
*[`.bazelrc` line 55 at r2](https://reviewable.io/reviews/DAIRLab/dairlib/351#-NgHHUf89rnhpncLEpf9:-NgJmDLEEs0lZUCngI2H:box5qsk) ([raw file](https://github.com/DAIRLab/dairlib/blob/9d7efbd389ba48a942453f13f6b6932cfd857233/.bazelrc#L55)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

This is with SNOPT 7.4? I've been using 7.6, which is also what's linked via the dairlib README

https://www.seas.upenn.edu/~posa/snopt/snopt7.6.tar.gz
</blockquote></details>

This is with 7.6, I'm speculating on whether or not that's the issue, since presumably a different version is tested.

**Comment by Brian-Acosta** [comment]
The SNOPT build error was fixed in [this drake PR](https://github.com/RobotLocomotion/drake/pull/20330). We can update the pegged revision and fix the build flag and merge this PR once that lands in an official release?

**Review by yangwill — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/351#-:-Nh7PRmW4vNCTGsKeS8W:bnfp4nl)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @ebianchi and @mposa)

**Pull request merged**
