### PR TITLE
fixing iostream dependency issues

### PR DESCRIPTION
**Pull request by yangwill**
Drake stopped including iostream in many of their libraries, places in our code where we used `std::cout` and `std::cerr` without include iostream started breaking. 

This includes iostream where we need it and removes outputs where it is unnecessary.

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308)

### CODE REVIEW

**Review by Brian-Acosta — CHANGES_REQUESTED** [review]
> Reviewed 58 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308)* status: all files reviewed, 4 unresolved discussions (waiting on @yangwill)

___
*[`examples/Cassie/osc/solver_settings/osqp_options_walking.yaml` line 13 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SETG397uPgN7Zf01p:-N5SETG397uPgN7Zf01q:b-84vq8e) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/examples/Cassie/osc/solver_settings/osqp_options_walking.yaml#L13)):*
> ```YAML
> polish: 1
> polish_refine_iter: 3
> verbose: 1
> ```

I assume this was for debugging and can be changed back?
___
*[`solvers/osqp_options_default.yaml` line 13 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SF2vV96AYkvyhrkga:-N5SF2vV96AYkvyhrkgb:buo9nmt) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/solvers/osqp_options_default.yaml#L13)):*
> ```YAML
> polish: 1
> polish_refine_iter: 3
> verbose: 1
> ```

Same here
___
*[`systems/controllers/osc/operational_space_control.cc` line 750 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SGEzfCtSJVTRzaMFr:-N5SGEzfCtSJVTRzaMFs:bdk1tgc) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/systems/controllers/osc/operational_space_control.cc#L750)):*
> ```cpp
>   // Solve the QP
> //  const MathematicalProgramResult result = solver_->Solve(*prog_);
>   auto osqp_solver = drake::solvers::OsqpSolver();
> ```

No more FastOsqpSolver?
___
*[`systems/controllers/osc/osc_tracking_data.cc` line 116 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SGQYb8dvjv9QOhOKE:-N5SGQYb8dvjv9QOhOKF:busgon3) ([raw file](https://github.com/dairlab/dairlib/blob/1481b3127f6cb5dfb80a51f637c8139792d1d5d3/systems/controllers/osc/osc_tracking_data.cc#L116)):*
> ```cpp
>   // Avoid repeated states
>   if (active_fsm_states_.count(state)) {
>     std::cout << "FSM state: " << state << " was already included in " << name_
> ```

Should we add an assertion to catch this?

**Review by Brian-Acosta — COMMENTED** [review]
Some questions (see individual comments) - Also make sure to update the pegged drake version so that it passes CI

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308#-:-N5SGmRQ03ziqClExFgQ:b-uu0zvf)* status: all files reviewed, 4 unresolved discussions (waiting on @yangwill)

**Review by Brian-Acosta — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308)* status: all files reviewed, 4 unresolved discussions (waiting on @yangwill)

___
*[`systems/controllers/osc/operational_space_control.cc` line 750 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SGEzfCtSJVTRzaMFr:-N8UrXrK13IL6rjx8Y2b:b-armxma) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/systems/controllers/osc/operational_space_control.cc#L750)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

No more FastOsqpSolver?
</blockquote></details>

Following up on this

**Review by Brian-Acosta — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308)* status: all files reviewed, 8 unresolved discussions (waiting on @yangwill)

___
*[`examples/Cassie/dispatcher_robot_in.cc` line 70 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UrpTv4MYJDkQXKxsR:-N8UrpTv4MYJDkQXKxsS:bj0l5sp) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/dispatcher_robot_in.cc#L70)):*
> ```cpp
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
> 
>   drake::lcm::DrakeLcm lcm_local;
> ```

Put the lcm url back to avoid issues with env variables
___
*[`examples/Cassie/dispatcher_robot_out.cc` line 161 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UsAPU70gRB-PTb96y:-N8UsAPU70gRB-PTb96z:bj0l5sp) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/dispatcher_robot_out.cc#L161)):*
> ```cpp
> 
>   DiagramBuilder<double> builder;
>   auto lcm = builder.AddSystem<drake::systems::lcm::LcmInterfaceSystem>();
> ```

Put the lcm url back to avoid issues with env variables
___
*[`examples/Cassie/run_controller_switch.cc` line 84 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UsEAiASuT2zQroNT0:-N8UsEAiASuT2zQroNT1:bj0l5sp) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/run_controller_switch.cc#L84)):*
> ```cpp
>   // Build the diagram
>   drake::systems::DiagramBuilder<double> builder;
>   auto lcm = builder.AddSystem<drake::systems::lcm::LcmInterfaceSystem>();
> ```

Put the lcm url back to avoid issues with env variables
___
*[`examples/Cassie/run_osc_walking_controller.cc` line 115 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UsHcD6KUbAKeCGghY:-N8UsHcD6KUbAKeCGghZ:bj0l5sp) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/run_osc_walking_controller.cc#L115)):*
> ```cpp
>   DiagramBuilder<double> builder;
> 
>   drake::lcm::DrakeLcm lcm_local;
> ```

Put the lcm url back to avoid issues with env variables

**Review by yangwill — COMMENTED** [review]
Fixed all the issues

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308#-:-N9bhbMkDR1rkSyQbhik:b7kypyx)* status: 46 of 63 files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta)

___
*[`examples/Cassie/dispatcher_robot_in.cc` line 70 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UrpTv4MYJDkQXKxsR:-N9Y-IxWDW3DfGZQS7i2:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/dispatcher_robot_in.cc#L70)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Put the lcm url back to avoid issues with env variables
</blockquote></details>

Done.
___
*[`examples/Cassie/dispatcher_robot_out.cc` line 161 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UsAPU70gRB-PTb96y:-N9Y-JomEDAPY_yClV0f:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/dispatcher_robot_out.cc#L161)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Put the lcm url back to avoid issues with env variables
</blockquote></details>

Done.
___
*[`examples/Cassie/run_controller_switch.cc` line 84 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UsEAiASuT2zQroNT0:-N9Y-Pru6qA4ev7Yvjt6:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/run_controller_switch.cc#L84)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Put the lcm url back to avoid issues with env variables
</blockquote></details>

Done.
___
*[`examples/Cassie/run_osc_walking_controller.cc` line 115 at r2](https://reviewable.io/reviews/dairlab/dairlib/308#-N8UsHcD6KUbAKeCGghY:-N9Y-UYW5KI7T8ocGEZs:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a92f2f2b07a7f9069ecca142f198acd554171aa2/examples/Cassie/run_osc_walking_controller.cc#L115)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Put the lcm url back to avoid issues with env variables
</blockquote></details>

Done.
___
*[`examples/Cassie/osc/solver_settings/osqp_options_walking.yaml` line 13 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SETG397uPgN7Zf01p:-N5SkhpK5RLnFQQppoXV:b-oz8o77) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/examples/Cassie/osc/solver_settings/osqp_options_walking.yaml#L13)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

I assume this was for debugging and can be changed back?
</blockquote></details>

Good catch
___
*[`solvers/osqp_options_default.yaml` line 13 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SF2vV96AYkvyhrkga:-N5Skn07BUPN9fyc3zfW:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/solvers/osqp_options_default.yaml#L13)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`systems/controllers/osc/operational_space_control.cc` line 750 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SGEzfCtSJVTRzaMFr:-N5SkurG9u-OGzXn0iON:bjxee0i) ([raw file](https://github.com/dairlab/dairlib/blob/0e755b3b6ab25918ac941d8019e3cdb83d4d8be0/systems/controllers/osc/operational_space_control.cc#L750)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

No more FastOsqpSolver?
</blockquote></details>

Another good catch, the new drake breaks FastOsqpSolver so I'll send another PR that reverts it.
___
*[`systems/controllers/osc/osc_tracking_data.cc` line 116 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SGQYb8dvjv9QOhOKE:-N5Sl8Gp6V2yl-2M4uo2:b-kmroik) ([raw file](https://github.com/dairlab/dairlib/blob/1481b3127f6cb5dfb80a51f637c8139792d1d5d3/systems/controllers/osc/osc_tracking_data.cc#L116)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Should we add an assertion to catch this?
</blockquote></details>

I thought that's what DRAKE_DEMAND does.

**Review by Brian-Acosta — APPROVED** [review]
Approved with minor comments

> Reviewed 3 of 5 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/308#-:-N9d2G_aD1L9n4FqjYDq:bpd71p1)* status: all files reviewed, 2 unresolved discussions (waiting on @yangwill)

___
*[`examples/Cassie/visualizer.cc` line 112 at r4](https://reviewable.io/reviews/dairlab/dairlib/308#-N9d0iaw6JiaxpnLQRlG:-N9d0iaw6JiaxpnLQRlH:b-qm9vfo) ([raw file](https://github.com/dairlab/dairlib/blob/bedf944bfa7ee8ca01623ff14eb3ad6bb546cd1f/examples/Cassie/visualizer.cc#L112)):*
> ```cpp
>   }
> 
>   DrakeVisualizer<double>::AddToBuilder(&builder, scene_graph, lcm);
> ```

I assume this fixes the DRAKE_VIEWER_DRAW  ttl?
___
*[`systems/controllers/osc/osc_tracking_data.cc` line 116 at r1](https://reviewable.io/reviews/dairlab/dairlib/308#-N5SGQYb8dvjv9QOhOKE:-N9d1nP50qs8WTtvaExT:b-98w18e) ([raw file](https://github.com/dairlab/dairlib/blob/1481b3127f6cb5dfb80a51f637c8139792d1d5d3/systems/controllers/osc/osc_tracking_data.cc#L116)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

I thought that's what DRAKE_DEMAND does.
</blockquote></details>

Ah I see the DRAKE_DEMAND right below lol. Can we just remove this then?

**Pull request merged**
