### PR TITLE
Adding function to construct vector from maps

### PR DESCRIPTION
**Pull request by yangwill**
I've need to use this functionality several times and had to copy in each case. It builds from the functions that already exist in multibody_utils so I thought it would fit well there.

### CODE REVIEW

**Comment by yangwill** [comment]
Good point. I can, but because there aren't any requirements on the map, the user can just input an empty `std::map<std::string, int>` for any fields they don't want converted. I'll add that in the documentation.

**Comment by yangwill** [comment]
Or would it make more sense to just have a single function that converts any std::map to a vector of strings? The occasions that I use this function are mainly to label the states of the trajectories I'm saving.

**Comment by yminchen** [comment]
I prefer the original implementation, since this function only converts a `map<string, int>` of which the `int` is non-repeating and "continuous" (no missing integer between any two)

**Comment by yangwill** [comment]
I changed the function to treat the state and inputs separately - I agree that it makes more sense this way.

**Pull request merged**
