### PR TITLE
Adding dircon specific API for saving/loading/visualizing trajectories

### PR DESCRIPTION
**Pull request by yangwill**
API for saving/loading trajectories.

Also addresses TODO in hybrid_dircon.cc:372. Drake added the option of concatenating trajectories to construct PiecewisePolynomials with discontinuities.

Not entirely happy with how I implemented `GetStateAndDerivativeSamples()`.

Features:
- Can save dircon trajectory in only two lines
- Can load and reconstruct either the state or input trajectory in only three lines

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/190)

### CODE REVIEW

**Comment by yangwill** [comment]
Not ready for review yet, need to clean up documentation.

**Comment by yangwill** [comment]
Ready for review!

**Comment by yangwill** [comment]
Ready for final review, @yminchen

**Review by yminchen — CHANGES_REQUESTED** [review]
Sorry about the late review! One comment on the binary files. I wonder if those files should stay outside of github?

In one of your commits, you said there is a bug in the new dircon. Is this bug fixed or reported somewhere? 

> Reviewed 2 of 11 files at r3, 16 of 19 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/190#-:-MH3kHpK575FGDXws7GD:bhsltye)* status: all files reviewed, 1 unresolved discussion (waiting on @yangwill)

___
*[examples/Cassie/saved_trajectories/jumping_0.2h_0.25d, line 0 at r5](https://reviewable.io/reviews/dairlab/dairlib/190#-MH3eMT-BHe94md2CXLB:-MH3eMT03552gow5NfRF:bmjvx47) ([raw file](https://github.com/dairlab/dairlib/blob/c84552191c827791ba228e981dc0848a582f2fc4/examples/Cassie/saved_trajectories/jumping_0.2h_0.25d#L0)):*
We should probably add a README.md file telling which urdf is used to generate the trajectories. 

Also, these two trajectory binary's size are about 49MB in total. Maybe we should avoid pushing it to Dairlib? One way is to add the files to the lab's google drive, and use this link format to download the shareable: https://drive.google.com/uc?export=download&id=TheFile'sID
Could either create a shell script to download the files or write it in c++?

**Review by yangwill — COMMENTED** [review]
Yes the bug was fixed, previously `get_evaluator_set()` returned a copy instead of a reference. Good point about the example saved trajectories I didn't realize that they were so large. I'll think of a way to host them outside of github.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/190#-:-MH44Lwv1u0GNc0Li7-X:b-y6zq0w)* status: all files reviewed, 1 unresolved discussion (waiting on @yangwill)

**Review by yangwill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/190)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @yminchen)

___
*[examples/Cassie/saved_trajectories/jumping_0.2h_0.25d, line  at r5](https://reviewable.io/reviews/dairlab/dairlib/190#-MH3eMT-BHe94md2CXLB:-MHd1lYt2mKjakTstByG:b-80ux8d) ([raw file](https://github.com/dairlab/dairlib/blob/c84552191c827791ba228e981dc0848a582f2fc4/examples/Cassie/saved_trajectories/jumping_0.2h_0.25d#L)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

We should probably add a README.md file telling which urdf is used to generate the trajectories. 

Also, these two trajectory binary's size are about 49MB in total. Maybe we should avoid pushing it to Dairlib? One way is to add the files to the lab's google drive, and use this link format to download the shareable: https://drive.google.com/uc?export=download&id=TheFile'sID
Could either create a shell script to download the files or write it in c++?
</blockquote></details>

I added the example dircon trajectories to the lab drive and removed them from git.

**Review by yminchen — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/190#-:-MHdENKT7mpdYS83rDFk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
