### PR TITLE
Add com visualization to connectTrajectoryVisualizer()

### PR DESCRIPTION
**Pull request by yminchen**
Changes: 
* Add COM visualization to `connectTrajectoryVisualizer` 
* Remove a deprecated method `ConnectDrakeVisualizer`

This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)

### CODE REVIEW

**Review by yangwill — CHANGES_REQUESTED** [review]
LGTM once the actual center of mass visualization code is cleaned up.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242#-:-MZZGGbG9AZZht62RYKp:blfpm55)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @yminchen)

___
*[multibody/visualization_utils.cc, line 43 at r1](https://reviewable.io/reviews/dairlab/dairlib/242#-MZZG1ZP7DcGPI3gIBgC:-MZZG1ZP7DcGPI3gIBgD:b-sfxb0c) ([raw file](https://github.com/dairlab/dairlib/blob/138e3398b8de3b40b8f9dbb7a3e934d6e749ae61/multibody/visualization_utils.cc#L43)):*
> ```cpp
>   if (ball_plant != nullptr) {
>     // Construct the ball plant
>     double radius = .02;
> ```

Can we make this a urdf? It will simplify the code. We can make this change in the multibody_visualizer as well.

**Review by yminchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @yangwill)

___
*[multibody/visualization_utils.cc, line 43 at r1](https://reviewable.io/reviews/dairlab/dairlib/242#-MZZG1ZP7DcGPI3gIBgC:-MZcPJuO7v9oqjr3hbww:b-scvv26) ([raw file](https://github.com/dairlab/dairlib/blob/138e3398b8de3b40b8f9dbb7a3e934d6e749ae61/multibody/visualization_utils.cc#L43)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Can we make this a urdf? It will simplify the code. We can make this change in the multibody_visualizer as well.
</blockquote></details>

I made a function that constructs this ball. Let me know if it's still necessary to create a urdf.

**Review by yangwill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @yminchen)

___
*[multibody/visualization_utils.cc, line 43 at r1](https://reviewable.io/reviews/dairlab/dairlib/242#-MZZG1ZP7DcGPI3gIBgC:-MZdcwrxBrGddQ_DzuXx:bwbmgkb) ([raw file](https://github.com/dairlab/dairlib/blob/138e3398b8de3b40b8f9dbb7a3e934d6e749ae61/multibody/visualization_utils.cc#L43)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I made a function that constructs this ball. Let me know if it's still necessary to create a urdf.
</blockquote></details>

I think this is fine, but I still think it's much cleaner to make it a urdf. There's nothing particularly special about the ball plant that the new function generates, so initializing it from a urdf seems to make a lot more sense.

**Review by yminchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @yangwill)

___
*[multibody/visualization_utils.cc, line 43 at r1](https://reviewable.io/reviews/dairlab/dairlib/242#-MZZG1ZP7DcGPI3gIBgC:-MZhqafxCMvoVj3099pV:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/138e3398b8de3b40b8f9dbb7a3e934d6e749ae61/multibody/visualization_utils.cc#L43)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

I think this is fine, but I still think it's much cleaner to make it a urdf. There's nothing particularly special about the ball plant that the new function generates, so initializing it from a urdf seems to make a lot more sense.
</blockquote></details>

done

**Review by yangwill — APPROVED** [review]
> Reviewed 7 of 14 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yminchen)

**Review by yangwill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yminchen)

**Review by yangwill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yminchen)

**Review by yangwill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yminchen)

**Pull request merged**
