### PR TITLE
add option for joint offsets to state estimator

### PR DESCRIPTION
**Pull request by Brian-Acosta**
This change is [Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/339)

### CODE REVIEW

**Review by yangwill — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/339)* status: all files reviewed, 4 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[`examples/Cassie/cassie_state_estimator.h` line 65 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6dNAH8mUb26Hbrd3p:-NO6dNAH8mUb26Hbrd3q:bdvv0bb) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/cassie_state_estimator.h#L65)):*
> ```objc
>       const multibody::KinematicEvaluatorSet<double>* left_contact_evaluator,
>       const multibody::KinematicEvaluatorSet<double>* right_contact_evaluator,
>       std::string joint_offset_yaml = "",
> ```

shouldn't need to store the filepath of the yaml in this class
___
*[`examples/Cassie/cassie_utils.cc` line 113 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6cRB1BE9jvz9oaeZb:-NO6cRB1BE9jvz9oaeZc:bqtz68y) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/cassie_utils.cc#L113)):*
> ```cpp
>   }
>   const auto pos_map = multibody::MakeNameToPositionsMap(plant);
>   const auto archive = drake::yaml::LoadYamlFile<
> ```

nitpick but better variable names would be helpful for `archive` and `entry`.
___
*[`examples/Cassie/cassie_utils.cc` line 113 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6cang3plcdAfLYtpD:-NO6cang3plcdAfLYtpE:b-eoko4f) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/cassie_utils.cc#L113)):*
> ```cpp
>   }
>   const auto pos_map = multibody::MakeNameToPositionsMap(plant);
>   const auto archive = drake::yaml::LoadYamlFile<
> ```

Instead of loading the yaml file here, i think it would be easier to read if we convert to a struct. It'll require more code but this way it's much more intuitive to understand the actual variable being passed. This would also address my comment above
___
*[`examples/Cassie/dispatcher_robot_out.cc` line 64 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6c4na7zKp_67WFsKc:-NO6c4na7zKp_67WFsKd:b-lrmtaw) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/dispatcher_robot_out.cc#L64)):*
> ```cpp
> DEFINE_double(contact_force_threshold, 60,
>               "Contact force threshold. Set to 140 for walking");
> DEFINE_string(joint_offset_yaml, "", "yaml with joint offset values");
> ```

a default value here would be helpful

**Review by Brian-Acosta — COMMENTED** [review]
Addressed comments and moved map -> joint offset from cassie_utils to multibody_utils

> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/339#-:-NOAbx_j7p_q6yzFd0Tl:b-4rt3em)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[`examples/Cassie/cassie_state_estimator.h` line 65 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6dNAH8mUb26Hbrd3p:-NOAbjdjBAPYidgHNtIB:bb6un1j) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/cassie_state_estimator.h#L65)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

shouldn't need to store the filepath of the yaml in this class
</blockquote></details>

Done
___
*[`examples/Cassie/dispatcher_robot_out.cc` line 64 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6c4na7zKp_67WFsKc:-NOAbU2Z6SiDazoQv__V:b-6gkwv5) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/dispatcher_robot_out.cc#L64)):*
> Instead of loading the yaml file here, i think it would be easier to read if we convert to a struct. It'll require more code but this way it's much more intuitive to understand the actual variable being passed. This would also address my comment above

An empty default value results in a offset of zero
___
*[`examples/Cassie/cassie_utils.cc` line 113 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6cRB1BE9jvz9oaeZb:-NOAbkj15W15oYtcXEDy:bb6un1j) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/cassie_utils.cc#L113)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

nitpick but better variable names would be helpful for `archive` and `entry`.
</blockquote></details>

Done
___
*[`examples/Cassie/cassie_utils.cc` line 113 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/339#-NO6cang3plcdAfLYtpD:-NOAblPW7CvAezDVGlLh:b-2rlh12) ([raw file](https://github.com/DAIRLab/dairlib/blob/ecd48ca95fca568390711b9cfe38f93896431e70/examples/Cassie/cassie_utils.cc#L113)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Instead of loading the yaml file here, i think it would be easier to read if we convert to a struct. It'll require more code but this way it's much more intuitive to understand the actual variable being passed. This would also address my comment above
</blockquote></details>

Done - passing a map per discussion today

**Review by yangwill — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/339#-:-NOKbg9SDhseVU-UHE0P:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yminchen)

**Comment by Brian-Acosta** [comment]
bug fix *

**Pull request merged**
