### PR TITLE
Safety checks

### PR DESCRIPTION
**Pull request by yangwill**
Adding check to shut off controller if the delay between messages is too large.
- Connecting a publisher for the status of the input supervisor (which if any of the safety checks are being violated)

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211)

### CODE REVIEW

**Comment by yangwill** [comment]
Ready for final review

**Review by yminchen — CHANGES_REQUESTED** [review]
Only minor comments

> Reviewed 6 of 11 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211#-:-MODcMCoEWDZWIGbswwN:b-oycjma)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/input_supervisor.h, line 73 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MODbaqN6aCHtTJ1x19E:-MODbaqN6aCHtTJ1x19F:b-7006tq) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/examples/Cassie/input_supervisor.h#L73)):*
> ```
>   // Sets the status bit to the current status
>   // 0b00  if no limits are being applied
> ```
I couldn't understand initially. Can you add more explanation here? (e.g. first bit is used for ..., the second bit is use for ...)
___
*[lcmtypes/lcmt_input_supervisor_status.lcm, line 10 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MODZwNjEGACpGPP9ECX:-MODZwNjEGACpGPP9ECY:b-eknax2) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/lcmtypes/lcmt_input_supervisor_status.lcm#L10)):*
> ```
>   int8_t vel_limit;
>   int8_t act_limit;
>   int8_t act_delay;
> ```

Can you add a comment on the time unit just to be clear?
___
*[systems/controllers/linear_controller.cc, line 38 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MOD_G8YD6eniGLPPM4U:-MOD_G8YD6eniGLPPM4V:b-oo0s8u) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/systems/controllers/linear_controller.cc#L38)):*
> ```cpp
>   }
>   VectorXd u =
>       config->GetK() * (x_tilde);
> ```

The code style here looks off?

**Review by yangwill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @yminchen)

___
*[examples/Cassie/input_supervisor.h, line 73 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MODbaqN6aCHtTJ1x19E:-MODcsZC9CKuG_tgZJww:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/examples/Cassie/input_supervisor.h#L73)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> ```
>   // Sets the status bit to the current status
>   // 0b00  if no limits are being applied
> ```
I couldn't understand initially. Can you add more explanation here? (e.g. first bit is used for ..., the second bit is use for ...)
</blockquote></details>

Done.
___
*[lcmtypes/lcmt_input_supervisor_status.lcm, line 10 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MODZwNjEGACpGPP9ECX:-MODdHgq4PaY8Q2nYi-e:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/lcmtypes/lcmt_input_supervisor_status.lcm#L10)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Can you add a comment on the time unit just to be clear?
</blockquote></details>

Done.
___
*[systems/controllers/linear_controller.cc, line 38 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MOD_G8YD6eniGLPPM4U:-MODdMYV7CaAIed-L15O:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/systems/controllers/linear_controller.cc#L38)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

The code style here looks off? 
</blockquote></details>

Done.

**Review by yminchen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/input_supervisor.cc, line 141 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmCn4D_9JhrxpKR3C:-MODmCn4D_9JhrxpKR3D:b-6f6k4r) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L141)):*
> ```cpp
>   output->utime = command->get_timestamp() * 1e6;
>   output->vel_limit =
>       context.get_discrete_state(status_vars_index_)[status_index_];
> ```

Can you explain what's the role for`vel_limit`? It seems to me that it's not used in `InputSupervisor`. 
___
*[examples/Cassie/input_supervisor.cc, line 148 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmUTv5BlmqS0v-zcK:-MODmUTv5BlmqS0v-zcL:bpveo6d) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L148)):*
> ```cpp
>       if (command_value > input_limit_ || command_value < -input_limit_) {
>         output->status += 2;
>         output->act_limit = 1;
> ```

nitpick: use `true` instead of `1` for readability 
___
*[examples/Cassie/input_supervisor.cc, line 160 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmV5j0hYHHQNrVIp2:-MODmV5j0hYHHQNrVIp3:bpveo6d) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L160)):*
> ```cpp
>       min_consecutive_failures_) {
>     output->status += 4;
>     output->shutdown = 1;
> ```

nitpick: use `true` instead of `1` for readability 
___
*[examples/Cassie/input_supervisor.cc, line 167 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODlLuL1iNowpjrjid_:-MODlLuL1iNowpjrjida:bpveo6d) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L167)):*
> ```cpp
>       kMaxControllerDelay)){
>     output->act_delay = 1;
>     output->shutdown = 1;
> ```

nitpick: use `true` instead of `1` for readability

**Review by yangwill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @yminchen)

___
*[examples/Cassie/input_supervisor.cc, line 141 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmCn4D_9JhrxpKR3C:-MOHLKzk0UeZ4Rmx_DIq:bh2q6y4) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L141)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Can you explain what's the role for`vel_limit`? It seems to me that it's not used in `InputSupervisor`. 
</blockquote></details>

It tracks whether the current state violates the velocity limits. The shutdown occurs if the velocity limit is reached more than `min_consecutive_failures` consecutive times.
___
*[examples/Cassie/input_supervisor.cc, line 148 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmUTv5BlmqS0v-zcK:-MOHLcdbEnazckXBiz0o:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L148)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

nitpick: use `true` instead of `1` for readability 
</blockquote></details>

Done.
___
*[examples/Cassie/input_supervisor.cc, line 160 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmV5j0hYHHQNrVIp2:-MOHLd-SDrpVqX5_1UaR:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L160)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

nitpick: use `true` instead of `1` for readability 
</blockquote></details>

Done.
___
*[examples/Cassie/input_supervisor.cc, line 167 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODlLuL1iNowpjrjid_:-MOHLdIi1TJXm6LYD4bv:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L167)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

nitpick: use `true` instead of `1` for readability 
</blockquote></details>

Done.

**Review by yminchen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/input_supervisor.cc, line 141 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmCn4D_9JhrxpKR3C:-MOI3Vff3uRJS8FHmn4-:b-u12m7v) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L141)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

It tracks whether the current state violates the velocity limits. The shutdown occurs if the velocity limit is reached more than `min_consecutive_failures` consecutive times.
</blockquote></details>

Why do we assign `context.get_discrete_state(status_vars_index_)[status_index_]` to both `output->status` and `output->vel_limit`?
___
*[examples/Cassie/input_supervisor.cc, line 167 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODlLuL1iNowpjrjid_:-MOI2L3R-ybEbL28PFZY:b-xr4v8u) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L167)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I believe you missed `act_delay`

**Review by yminchen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/input_supervisor.cc, line 141 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODmCn4D_9JhrxpKR3C:-MOI9Zsb75TO0rVF7Ymi:b-esqhdm) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L141)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Why do we assign `context.get_discrete_state(status_vars_index_)[status_index_]` to both `output->status` and `output->vel_limit`?
</blockquote></details>

It took me awhile to understand the algorithm. I think we can add `int()` and `bool()` to increase readability. 
Something like this might work:
  output->status =
      int(context.get_discrete_state(status_vars_index_)[status_index_]);
  output->vel_limit =
      bool(context.get_discrete_state(status_vars_index_)[status_index_]);
___
*[examples/Cassie/input_supervisor.cc, line 167 at r3](https://reviewable.io/reviews/dairlab/dairlib/211#-MODlLuL1iNowpjrjid_:-MOIC2_9CgrQu8jhbN11:bm1zsy5) ([raw file](https://github.com/dairlab/dairlib/blob/bf248f65af9e4575775da0ea8657535caefb2819/examples/Cassie/input_supervisor.cc#L167)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I believe you missed `act_delay` 
</blockquote></details>

`output->act_delay = true;`
___
*[examples/Cassie/input_supervisor.cc, line 204 at r4](https://reviewable.io/reviews/dairlab/dairlib/211#-MOIAANE511OXe6EACpZ:-MOIAANE511OXe6EACp_:b-uow1o0) ([raw file](https://github.com/dairlab/dairlib/blob/adca4d64ab3ca9f1f499977c8d02060f3c5a7b34/examples/Cassie/input_supervisor.cc#L204)):*
> ```cpp
>           1;
>       discrete_state->get_mutable_vector(status_vars_index_)[status_index_] =
>           true;
> ```

Continuing the last comment, I think we can add `double()` here and add a comment that double(true) returns 1.
___
*[examples/Cassie/input_supervisor.cc, line 219 at r4](https://reviewable.io/reviews/dairlab/dairlib/211#-MOIATAUCYM_Nx39kfza:-MOIATAUCYM_Nx39kfzb:b-b0343g) ([raw file](https://github.com/dairlab/dairlib/blob/adca4d64ab3ca9f1f499977c8d02060f3c5a7b34/examples/Cassie/input_supervisor.cc#L219)):*
> ```cpp
>           0;
>       discrete_state->get_mutable_vector(status_vars_index_)[status_index_] =
>           false;
> ```

Continuing the last comment, I think we can add `double()` here and add a comment that double(false) returns 0.
___
*[lcmtypes/lcmt_input_supervisor_status.lcm, line 10 at r2](https://reviewable.io/reviews/dairlab/dairlib/211#-MODZwNjEGACpGPP9ECX:-MOIAZHg0a7903_SF8D-:b-ma8nph) ([raw file](https://github.com/dairlab/dairlib/blob/89ab99caf8efbcbe51e1553d61cc1f12388ee59e/lcmtypes/lcmt_input_supervisor_status.lcm#L10)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh I was confused about the unit of `act_delay` instead of `utime` earlier. Now that we declare `act_delay` in boolean, it's clear what its role is.

**Review by yminchen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/211#-:-MOILduB9s0dtS-VCYAD:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @yangwill)

**Pull request merged**
