### PR TITLE
minimal tracking controller for centroidal plans

### PR DESCRIPTION
**Pull request by yangwill**
Needs further testing, but this is the first PR to track plans generated with centroidal mpc

- - -
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/321)

### CODE REVIEW

**Review by ShaneRozenLevy — COMMENTED** [review]
Looks good. A few small changes that I would consider mostly nits. We should still try to figure out why the trajectory on your end was wonky, while on my end it was fine.

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/321#-:-NEJ7HjJ7KAVVuxEOJmB:bjedsrl)* status: all files reviewed, 15 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[`examples/Cassie/centroidal_mpc_tracking_controller.cc` line 133 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ4L1p0bo9bh5HN8XZ:-NEJ4L1p0bo9bh5HN8X_:b-ge7t11) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/centroidal_mpc_tracking_controller.cc#L133)):*
> ```cpp
> 
>   std::unordered_map<int, int> contact_state_to_fsm_map;
>   int FLIGHT = 0;
> ```

nit: make const
___
*[`examples/Cassie/centroidal_mpc_tracking_controller.cc` line 147 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ5LOdEXlfl2Fbs0A5:-NEJ5LOdEXlfl2Fbs0A6:b-r4zf07) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/centroidal_mpc_tracking_controller.cc#L147)):*
> ```cpp
>   auto state_reference_receiver =
>       builder.AddSystem<LcmTrajectoryReceiver>("state_traj");
>   auto contact_force_reference_receiver =
> ```

Am I correct that at this time this is only used for determining contact sequence and not as something tracked with the osc?
___
*[`examples/Cassie/centroidal_mpc_tracking_controller.cc` line 152 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ2Rls7rYmPTS_TjNI:-NEJ2Rls7rYmPTS_TjNJ:b-o3d17) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/centroidal_mpc_tracking_controller.cc#L152)):*
> ```cpp
>   auto state_receiver =
>       builder.AddSystem<systems::RobotOutputReceiver>(plant_w_spr);
>   // This actually outputs the target position of the pelvis not the true
> ```

If we want to track com position, that is present in the kcmpc decision variables. It just depends on whats easier to track with the osc, com position or pelvis position.
___
*[`examples/Cassie/kinematic_centroidal_mpc/cassie_kcmpc_trajopt.cc` line 337 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ1NoQ-GNcLk-Df4nI:-NEJ1NoQ-GNcLk-Df4nJ:b-djy8ux) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/cassie_kcmpc_trajopt.cc#L337)):*
> ```cpp
>   std::cout << "Solving optimization\n\n";
>   const auto pp_xtraj = mpc.Solve();
>   mpc.SaveSolutionToFile("kcmpc_solution");
> ```

Maybe we should include the relative path to where the tracking controller will look for the trajectory? 
___
*[`examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.h` line 15 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ4cvd0f6O0lEcHmub:-NEJ4cvd0f6O0lEcHmuc:bdg85pb) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.h#L15)):*
> ```objc
> namespace systems {
> 
> /// ContactScheduler
> ```

I like how elegant this is. 
___
*[`examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc` line 32 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ6U1iBdLs27Bb7ysC:-NEJ6U1iBdLs27Bb7ysD:b-6urgw7) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc#L32)):*
> ```cpp
>   contact_force_trajectory_input_port_ =
>       this->DeclareAbstractInputPort(
>               "lambda_reference",
> ```

nit, probably should rename, or add as argument
___
*[`examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc` line 54 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ4y7W8CJDZ1YOY2z1:-NEJ4y7W8CJDZ1YOY2z2:be51r9w) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc#L54)):*
> ```cpp
> 
>   /// shift the active contacts to form contact state
>   int contact_state = ((desired_contact[2] > 0) * 1 << 0)
> ```

Do we want an epsilon here?
___
*[`examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc` line 54 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ53r5CH3P5-4qOu0w:-NEJ53r5CH3P5-4qOu0x:boqykux) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc#L54)):*
> ```cpp
> 
>   /// shift the active contacts to form contact state
>   int contact_state = ((desired_contact[2] > 0) * 1 << 0)
> ```

nit, make const
___
*[`examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.h` line 11 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ2uyU2bcF-EZ1vAN4:-NEJ2uyU2bcF-EZ1vAN5:b-spy8tr) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.h#L11)):*
> ```objc
> namespace dairlib {
> 
> class KinematicTrajectoryGenerator : public drake::systems::LeafSystem<double> {
> ```

Can you add some comments about the goal of this class/what it does? I assume it takes a robot state trajectory and outputs the necessary task space trajectory for the osc?
___
*[`examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.h` line 57 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ3b0cErBzEIlwDaLB:-NEJ3b0cErBzEIlwDaLC:b-r8posg) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.h#L57)):*
> ```objc
> };
> 
> }  // namespace dairlib::examples::osc_jump
> ```

nit, wrong namespace
___
*[`examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.cc` line 52 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ6Z922zfCjQ6tzu1H:-NEJ6Z922zfCjQ6tzu1I:b2qgikn) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.cc#L52)):*
> ```cpp
>   state_trajectory_port_ =
>       this->DeclareAbstractInputPort(
>               "lambda_reference",
> ```

nit: probably should rename or add as argument
___
*[`examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.cc` line 102 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ3f5r8cFGf_5tExTa:-NEJ3f5r8cFGf_5tExTb:b-xt8nf) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.cc#L102)):*
> ```cpp
>       (PiecewisePolynomial<double>*)dynamic_cast<PiecewisePolynomial<double>*>(
>           traj);
> //  auto generated_trajectory = PiecewisePolynomial<double>::CubicHermite(segment_times,
> ```

It would be nice to be able to template this class by the order of the spline, but I don't think the have a consistent constructor we would use.
___
*[`examples/Cassie/kinematic_centroidal_mpc/trajectory_passthrough.h` line 27 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ6iolDj87QoGVORgu:-NEJ6iolDj87QoGVORgv:b20vk7m) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/trajectory_passthrough.h#L27)):*
> ```objc
> };
> 
> }  // namespace dairlib::examples::osc_jump
> ```

nit: wrong comment
___
*[`examples/Cassie/kinematic_centroidal_mpc/trajectory_passthrough.cc` line 14 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ6bIV5Gjm6IGCJNh8:-NEJ6bIV5Gjm6IGCJNh9:b-ye4ibf) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/trajectory_passthrough.cc#L14)):*
> ```cpp
>   trajectory_port_ =
>       this->DeclareAbstractInputPort(
>               "lambda_reference",
> ```

probably should rename or use as input



_Code quote:_
```cpp
lambda
```
___
*[`systems/controllers/kinematic_centroidal_mpc/kinematic_centroidal_mpc.cc` line 263 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ-dbX15Gj5MdVBAf_:-NEJ-dbX15Gj5MdVBAfa:b-6x9hed) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/systems/controllers/kinematic_centroidal_mpc/kinematic_centroidal_mpc.cc#L263)):*
> ```cpp
> 
> drake::trajectories::PiecewisePolynomial<double> KinematicCentroidalMPC::Solve() {
> //  drake::solvers::MathematicalProgramResult result;
> ```

nit: rm this line

**Review by yangwill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/321)* status: all files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta and @ShaneRozenLevy)

___
*[`examples/Cassie/centroidal_mpc_tracking_controller.cc` line 147 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ5LOdEXlfl2Fbs0A5:-NELw9aPBeLd6SPyZ2IK:b-yawcmd) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/centroidal_mpc_tracking_controller.cc#L147)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

Am I correct that at this time this is only used for determining contact sequence and not as something tracked with the osc?
</blockquote></details>

Yes right now it is only used to determine contact, but eventually can be tracked with the OSC. 
___
*[`examples/Cassie/centroidal_mpc_tracking_controller.cc` line 152 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ2Rls7rYmPTS_TjNI:-NELwK3GA7UIpVRaovTD:bqhucmh) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/centroidal_mpc_tracking_controller.cc#L152)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

If we want to track com position, that is present in the kcmpc decision variables. It just depends on whats easier to track with the osc, com position or pelvis position.
</blockquote></details>

We have differing preferences within DAIRlab, I've always defaulted to tracking the pelvis because it's slightly less sensitive to the position of the swing foot, though we haven't numerically verified this and other controllers in the lab have successfully tracked the CoM.
___
*[`examples/Cassie/kinematic_centroidal_mpc/cassie_kcmpc_trajopt.cc` line 337 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ1NoQ-GNcLk-Df4nI:-NELzAT80gMyUocWfSNJ:b-bmuaot) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/cassie_kcmpc_trajopt.cc#L337)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

Maybe we should include the relative path to where the tracking controller will look for the trajectory? 
</blockquote></details>

Good point, changed it to `examples/Cassie/saved_trajectories/kcmpc_solution`.
___
*[`examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.h` line 15 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ4cvd0f6O0lEcHmub:-NELzPLl3iW0EYj65UxZ:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.h#L15)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

I like how elegant this is. 
</blockquote></details>

Done.
___
*[`examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc` line 54 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ4y7W8CJDZ1YOY2z1:-NELzg3FCDJ5UvREre5v:b59m4dk) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/contact_scheduler.cc#L54)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

Do we want an epsilon here?
</blockquote></details>

good point, done
___
*[`examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.h` line 11 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ2uyU2bcF-EZ1vAN4:-NEM1nrG1XDerL88AyE6:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.h#L11)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

Can you add some comments about the goal of this class/what it does? I assume it takes a robot state trajectory and outputs the necessary task space trajectory for the osc?
</blockquote></details>

Done.
___
*[`examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.cc` line 102 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ3f5r8cFGf_5tExTa:-NEM-gaA-Cr96yzuOM-e:b-r32mf5) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/kinematic_trajectory_generator.cc#L102)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

It would be nice to be able to template this class by the order of the spline, but I don't think the have a consistent constructor we would use.
</blockquote></details>

I think our choice will depend on whether we use collocation, first order hold should give the exact solution if we use euler integration, but cubichermite is more accurate if we use collocation. I'll leave a TODO to make sure we don't forget to use the proper spline construction
___
*[`examples/Cassie/kinematic_centroidal_mpc/trajectory_passthrough.cc` line 14 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEJ6bIV5Gjm6IGCJNh8:-NEM0U7zASTEVN2Exq6R:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/kinematic_centroidal_mpc/trajectory_passthrough.cc#L14)):*
<details><summary><i>Previously, ShaneRozenLevy wrote…</i></summary><blockquote>

probably should rename or use as input
</blockquote></details>

Done.

**Review by Brian-Acosta — COMMENTED** [review]
> Reviewed 3 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/321)* status: 20 of 28 files reviewed, 9 unresolved discussions (waiting on @ShaneRozenLevy and @yangwill)

___
*[`examples/Cassie/BUILD.bazel` line 352 at r1](https://reviewable.io/reviews/dairlab/dairlib/321#-NEM0_6v1Cktgq8l7svX:-NEM0_6v1Cktgq8l7svY:b-fwn29u) ([raw file](https://github.com/dairlab/dairlib/blob/a6ba1d18f95b90d05e131da9ca213a0f33947781/examples/Cassie/BUILD.bazel#L352)):*
> ```Starlark
> 
> cc_binary(
>     name = "centroidal_mpc_tracking_controller",
> ```

nit -can you change this binary name to `run_centroidal_mpc_tracking_controller` to match the rest of the OSC diagrams

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/321)* status: 20 of 28 files reviewed, 10 unresolved discussions (waiting on @ShaneRozenLevy and @yangwill)

___
*[`bindings/pydairlib/lcm/visualization/visualize_trajectory.py` line 62 at r2](https://reviewable.io/reviews/dairlab/dairlib/321#-NEM2IHTA-JipvYf6qEM:-NEM2IHTA-JipvYf6qEN:b-x8v8t1) ([raw file](https://github.com/dairlab/dairlib/blob/e21fb48aa71b4176e88873a83ee930fd2c0bcb5d/bindings/pydairlib/lcm/visualization/visualize_trajectory.py#L62)):*
> ```Python
>     state_traj = PiecewisePolynomial.FirstOrderHold(lcm_state_traj.time_vector, lcm_state_traj.datapoints[:37, :])
>     contact_force_traj = PiecewisePolynomial.FirstOrderHold(lcm_contact_force_traj.time_vector, lcm_contact_force_traj.datapoints[:12, :])
>     # plot_trajectory(state_traj, 'state', 37)
> ```

can we add this to the params?

**Comment by ShaneRozenLevy** [comment]
LGTM (I can't actually approve)

**Pull request merged**
