### PR TITLE
add sugar for velocity and acceleration level holonomic constraints

### PR DESCRIPTION
**Pull request by Brian-Acosta**
Add sugar for velocity and acceleration level holonomic constraints in MultibodyProgram

- - -
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/312)

### CODE REVIEW

**Review by Brian-Acosta — COMMENTED** [review]
nit

**Review by mposa — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/312)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[`examples/Cassie/cassie_fixed_point_solver.h` line 56 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hm0jq0jzRKQ5HrGY3:-N9Hm0jq0jzRKQ5HrGY4:b-bv7zxs) ([raw file](https://github.com/dairlab/dairlib/blob/f2851c773dd2399f4d0379d0d28d70fe1274f437/examples/Cassie/cassie_fixed_point_solver.h#L56)):*
> ```objc
>     Eigen::VectorXd* u_result, Eigen::VectorXd* lambda_result);
> 
> /// Constraint for CassieInitStateSolver
> ```

Is anything about this constraint specific to Cassie? A bit hard to tell, as its missing documentation, but it seems like a "constraint-ified" version of the `vdot` calculation.



_Code quote:_
```objc
    Eigen::VectorXd* lambda_result, std::string visualize_model_urdf = "");

/// Solve for a dynamically feasible state given Cassie's pelvis xy velocity.
/// This class is similar to CassieFixedPointSolver expect for the target pelvis
/// velocity.
void CassieInitStateSolver(
```
___
*[`examples/Cassie/cassie_fixed_point_solver.h` line 76 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hme4A5nmN_aHDLA31:-N9Hme4A5nmN_aHDLA32:b-7avbp1) ([raw file](https://github.com/dairlab/dairlib/blob/f2851c773dd2399f4d0379d0d28d70fe1274f437/examples/Cassie/cassie_fixed_point_solver.h#L76)):*
> ```objc
> 
> /// Constraint for CassieInitStateSolver
> class BodyPointVelConstraint
> ```

Also missing documentation, and also does not seem Cassie-specific.
___
*[`multibody/multibody_solvers.h` line 99 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hk60e-zESjU08wxkS:-N9Hk60e-zESjU08wxkT:brbmkss) ([raw file](https://github.com/dairlab/dairlib/blob/5ceb39dc8772d69d05f04a276732d1758519b403/multibody/multibody_solvers.h#L99)):*
> ```objc
> 
>   /// Adds a holonomic kinematic constraint at the position, velocity,
>   /// and acceleration level, and returns a vecotr of constraint bindings, one
> ```

"vecotr"
___
*[`multibody/multibody_solvers.cc` line 105 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9HkbFt5Cwg0CDrF6gg:-N9HkbFt5Cwg0CDrF6gh:b-1f742z) ([raw file](https://github.com/dairlab/dairlib/blob/5ceb39dc8772d69d05f04a276732d1758519b403/multibody/multibody_solvers.cc#L105)):*
> ```cpp
> 
> template <typename T>
> std::vector<Binding<Constraint>> MultibodyProgram<T>::AddHolonomicConstraint(
> ```

Can this method just re-use the other AddKinematicXX constraints?

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/312)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @mposa and @yangwill)

___
*[`examples/Cassie/cassie_fixed_point_solver.h` line 56 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hm0jq0jzRKQ5HrGY3:-N9HxqXKEIg3Cwvx7m6-:b-f08lqu) ([raw file](https://github.com/dairlab/dairlib/blob/f2851c773dd2399f4d0379d0d28d70fe1274f437/examples/Cassie/cassie_fixed_point_solver.h#L56)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

Is anything about this constraint specific to Cassie? A bit hard to tell, as its missing documentation, but it seems like a "constraint-ified" version of the `vdot` calculation.
</blockquote></details>

To be clear, this PR *removes* this constraint since 
1) It's not specific to Cassie 
2) It's only use duplicates the functionality of AddKinematicAccelerationConstraint
___
*[`examples/Cassie/cassie_fixed_point_solver.h` line 76 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hme4A5nmN_aHDLA31:-N9HyR1v7sYLPBwnNGbp:bqf2t5) ([raw file](https://github.com/dairlab/dairlib/blob/f2851c773dd2399f4d0379d0d28d70fe1274f437/examples/Cassie/cassie_fixed_point_solver.h#L76)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

Also missing documentation, and also does not seem Cassie-specific.
</blockquote></details>

Similar to above, less general duplicate of AddKinematicVelocityConstraint
___
*[`multibody/multibody_solvers.h` line 99 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hk60e-zESjU08wxkS:-N9Hz0Ne0AHwHzn99_iQ:b-886gsx) ([raw file](https://github.com/dairlab/dairlib/blob/5ceb39dc8772d69d05f04a276732d1758519b403/multibody/multibody_solvers.h#L99)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

"vecotr"
</blockquote></details>

Fixed
___
*[`multibody/multibody_solvers.cc` line 105 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9HkbFt5Cwg0CDrF6gg:-N9Hz1FE5nQt7U_3El_x:b2nhswv) ([raw file](https://github.com/dairlab/dairlib/blob/5ceb39dc8772d69d05f04a276732d1758519b403/multibody/multibody_solvers.cc#L105)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

Can this method just re-use the other AddKinematicXX constraints?
</blockquote></details>

Yep

**Review by mposa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/312)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @mposa, and @yangwill)

___
*[`examples/Cassie/cassie_fixed_point_solver.h` line 56 at r1](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Hm0jq0jzRKQ5HrGY3:-N9XrEsZCGWg05tRBwmC:b-85i63v) ([raw file](https://github.com/dairlab/dairlib/blob/f2851c773dd2399f4d0379d0d28d70fe1274f437/examples/Cassie/cassie_fixed_point_solver.h#L56)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

To be clear, this PR *removes* this constraint since 
1) It's not specific to Cassie 
2) It's only use duplicates the functionality of AddKinematicAccelerationConstraint
</blockquote></details>

LGTM.
___
*[`multibody/multibody_solvers.h` line 98 at r3](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Xs3bnEBkbVTG0dsp0:-N9Xs3bo5fk46vrDeDBU:bev5nbo) ([raw file](https://github.com/dairlab/dairlib/blob/f992d59f56a9ecca71619d0923a57bcb69eeb43e/multibody/multibody_solvers.h#L98)):*
> ```objc
>       const drake::solvers::VectorXDecisionVariable& lambda);
> 
>   /// Adds a holonomic kinematic constraint at the position, velocity,
> ```

Make it clear how this method relates to the pos/vel/accel constraints?

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/312)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @mposa and @yangwill)

___
*[`multibody/multibody_solvers.h` line 98 at r3](https://reviewable.io/reviews/dairlab/dairlib/312#-N9Xs3bnEBkbVTG0dsp0:-N9d-rr96Pn_K305sA3h:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f992d59f56a9ecca71619d0923a57bcb69eeb43e/multibody/multibody_solvers.h#L98)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

Make it clear how this method relates to the pos/vel/accel constraints?
</blockquote></details>

Done.

**Review by mposa — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/312#-:-N9h7oSd1VuRyxFK2kSP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangwill)

**Pull request merged**
