### PR TITLE
Use SetXXXIfNew to avoid making the cache dirty

### PR DESCRIPTION
**Pull request by yminchen**
Changes: 
* Use `SetXXXIfNew` functions to reuse Drake's context cache
* Fix a bug in `multibody_sim.cc`
* Modify OSC to use external `Context` as an option

------
Here is a benchmark of the computation time per lcm message before and after using `SetXXXIfNew`: 
|        | standing controller averaged eval time (ms) | walking controller averaged eval time (ms) |
|--------|---------------------------------------------|--------------------------------------------|
| Before | 1.209                                       | 1.17                                       |
| After  | 0.888                                       | 1.10                                       |

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/186)

### CODE REVIEW

**Comment by yminchen** [comment]
Btw, I measured the solve time of OSQP under different settings:

|                                           | Runtime of Solve() |
|-------------------------------------------|---------------------|
| Without warm start                        | 0.72 ms             |
| Warm start both primal and dual variables | 0.69 ms             |

The two tests above are with 200Hz of simulation publish rate.

| Simulation publish rate | Runtime of Solve() |
|-------------------------|---------------------|
| 200 Hz                  | 0.69 ms             |
| 500 Hz                  | 0.58 ms             |
| 1000 Hz                 | 0.54 ms*             |

The three tests above are with OSQP warm start.
\* The average eval time of the whole diagram per iteration is about 0.93 ms

**Comment by mposa** [comment]
How far away is #158 from being approved?

**Comment by yminchen** [comment]
@mposa I just approved it, although some conflicts need to be resolved

**Comment by yminchen** [comment]
@mposa I think #172 is ready for a squash merge. I will merge master into this PR after #172

**Comment by yminchen** [comment]
@yangwill I also modified OSC to use external `Context` as an option, although the constructor looks messier

**Pull request merged**
