### PR TITLE
Express redundant constraints in local frame

### PR DESCRIPTION
**Pull request by yminchen**
Built upon #266. 

I templated `OscViewFrame` so that I could use it in `WorldPointEvaluator`

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/267)

### CODE REVIEW

**Review by yangwill — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/267)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @yminchen)

___
*[multibody/kinematic/world_point_evaluator.h, line 3 at r1](https://reviewable.io/reviews/dairlab/dairlib/267#-Moe0OWg6TU3B6tuI5oL:-Moe0OWh8qnE5963mNkK:bc7c4jo) ([raw file](https://github.com/dairlab/dairlib/blob/56b08435a54219a1249a04239ad8c1b374206c9b/multibody/kinematic/world_point_evaluator.h#L3)):*
> ```objc
> #pragma once
> #include "multibody/kinematic/kinematic_evaluator.h"
> #include "systems/controllers/osc/osc_view_frame.h"
> ```

Let's rename this so it makes sense when we use it in more general classes.

**Review by yminchen — COMMENTED** [review]
I renamed it to `ViewFrame` and moved it inside `multibody` folder

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/267#-:-MojQm1j5EikZZIzhClH:b-c28t44)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @yangwill, and @yminchen)

**Review by yangwill — COMMENTED** [review]
In sim, the default orientation is a negative 90 degrees turn around the z-axis

> Reviewed 5 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/267#-:-Mojl0rs7sJbuTTm-Vse:b-hw7eok)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @yangwill, and @yminchen)

**Review by yminchen — COMMENTED** [review]
Thanks for catching this! It's default to walking in place now

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/267#-:-MojpNFX4l3UzFG10BTy:bd4g837)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @yangwill, and @yminchen)

**Comment by Brian-Acosta** [comment]
Does it still make sense to call it a WorldPointEvaluator if you can set a ViewFrame which is not the world frame? 
Would it be better to call it a ContactPointEvaluator?

**Comment by yminchen** [comment]
I think the class name is appropriate, since it gives us a point position expressed in the world frame. `ViewFrame` is only used to rotate this vector.

This class is also quite general, so naming it as `ContactPointEvaluator` might be a bit misleading.

**Review by yangwill — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/267#-:-MooEgcIAobuKxmP1uV4:bnfp4nl)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @yangwill, and @yminchen)

**Pull request merged**
