### PR TITLE
virtual remote only

### PR DESCRIPTION
**Pull request by Brian-Acosta**
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/222)

### CODE REVIEW

**Review by yangwill — APPROVED** [review]
LGTM after removing the pydairlib dependency

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/222#-:-MQT6gpk72NIkuiEX450:bc35e6w)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @yangwill)

___
*[examples/Cassie/BUILD.bazel, line 459 at r1](https://reviewable.io/reviews/dairlab/dairlib/222#-MQT2drA07KL_3JF0QGI:-MQT2drB8VyJ7exRE-rF:b-ydb8o) ([raw file](https://github.com/dairlab/dairlib/blob/75b43a91fb1d15a85f42aa87bcdc9b1467a99f57/examples/Cassie/BUILD.bazel#L459)):*
> ```Starlark
>     main = "cassie_virtual_remote.py",
>     deps = [
>         "//bindings/pydairlib",
> ```

Don't need this dependency

**Comment by mposa** [comment]
I'm OK merging this as-is, but as it does add a new dependency (pygame), we likely need some updates to our build instructions/process.

**Review by yangwill — COMMENTED** [review]
Hmm, I may have had pygame installed previously and that's why the build process was seamless but my anecdotal experience was all I had to do was checkout and build the python binary and the remote worked.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/222#-:-MQT9Mh85KOifF-If6x5:b-min74h)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta)

**Comment by mposa** [comment]
I was mostly going off the comments in the code here. However, a quick search over at Drake https://github.com/RobotLocomotion/drake/search?q=pygame&type= shows a pygame repository there. Can we piggy back off that here?

We could also add a unit test here, and the CI will check if the Docker image has pygame (my system also does, but who knows why).

**Comment by Brian-Acosta** [comment]
I'll go ahead and remove the pydairlib dependency for cleanliness' sake and merge. Thanks all. I looked at piggybacking off of drake's pygame dependency and couldn't get it working but maybe someone more familiar with Bazel could.

**Pull request merged**
