### PR TITLE
Move walking parameters to the yaml file

### PR DESCRIPTION
**Pull request by yminchen**
co-authored by @yangwill.

This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)

### CODE REVIEW

**Comment by yminchen** [comment]
I also updated the radio command because there are many parameters in `HighLevelCommand`.

**Review by yangwill — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @yminchen)

___
*[examples/Cassie/run_osc_walking_controller.cc, line 112 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2aCFa58HutzHObg4y:-MR2aCFa58HutzHObg4z:bnkzl1k) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L112)):*
> ```cpp
>   double ss_time;
>   double ds_time;
>   double k_ff_lateral;
> ```

We need to rename these variables:
`k_fb_lateral` -> `k_vel_lateral`
___
*[examples/Cassie/run_osc_walking_controller.cc, line 128 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2adN87dY-E0TrDh90:-MR2adN87dY-E0TrDh91:bb4f545) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L128)):*
> ```cpp
>   double global_target_position_x;
>   double global_target_position_y;
>   double params_of_no_turning1;
> ```

Remind me what these parameters are? It's related to global position tracking right?
___
*[examples/Cassie/run_osc_walking_controller.cc, line 135 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2cYnyA5sNIcNNwz3x:-MR2cYnyA5sNIcNNwz3y:bb16h2z) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L135)):*
> ```cpp
> 
>   template <typename Archive>
>   void Serialize(Archive* a) {
> ```

We can move this to another class - not needed for this PR, but just worth noting in the future.
___
*[examples/Cassie/osc/high_level_command.cc, line 119 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2dRgy31m_vuvmz8NG:-MR2dRgy31m_vuvmz8NH:b24rmho) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L119)):*
> ```cpp
>     //                  2: lateral_vel (left joystick left/right)
>     Vector3d des_vel;
>     des_vel << -1 * vel_scale_rot_ * cassie_out->pelvis.radio.channel[3],
> ```

move the negatives out of this class and into the gains
___
*[examples/Cassie/osc/high_level_command.cc, line 167 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2daMtATSpM_tVcQIQ:-MR2daMtATSpM_tVcQIR:ba0dnl6) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L167)):*
> ```cpp
>   double des_yaw_vel =
>       kp_yaw_ * (desired_yaw - approx_pelvis_yaw) + kd_yaw_ * (-yaw_vel);
>   des_yaw_vel = std::min(vel_max_yaw_, std::max(-vel_max_yaw_, des_yaw_vel));
> ```

why is there a negative here? I would expect `-vel_max_yaw_` to be smaller than `vel_max_yaw`
___
*[examples/Cassie/osc/high_level_command.cc, line 173 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2dxwN4v3XMdwpkSs6:-MR2dxwODQ141HNUT_Gy:bmzm56n) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L173)):*
> ```cpp
>                                (global_com_pos_to_target_pos.norm() -
>                                 params_of_no_turning_(1))));
>   double desired_filtered_yaw_vel = (1 - weight) * 0 + weight * des_yaw_vel;
> ```

PR for another time, but I think we need to combine the global yaw tracking with the hip yaw tracking. Otherwise they will conflict with each other. Yukai's paper has a good method for how to select the desired hip yaw from the desired turning speed.

**Review by yangwill — COMMENTED** [review]
Midway through the review. Looks good enough to use in `cassie_experimental`, needs polishing for when we merge into `master` though.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224#-:-MR2ePvnD2zqJSrQWyu0:bxsahmz)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @yminchen)

**Review by yminchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @yangwill)

___
*[examples/Cassie/run_osc_walking_controller.cc, line 112 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2aCFa58HutzHObg4y:-MR3F6nL2STux4jk0AJe:bxqqavh) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L112)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

We need to rename these variables:
`k_fb_lateral` -> `k_vel_lateral`
</blockquote></details>

How about rename them to `k_vel_ff_lateral` and `k_vel_fb_lateral`?
___
*[examples/Cassie/run_osc_walking_controller.cc, line 128 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2adN87dY-E0TrDh90:-MR3QQPb6q4hFwCB0T24:b-ws1cyz) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L128)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Remind me what these parameters are? It's related to global position tracking right?
</blockquote></details>

These two are a logistic function's parameters. I wanted Cassie to stop turning (tracking desired global yaw angle) once it's close enough to the target position. I blend the current yaw position and desired yaw position (this might not be the best choice), and the logistic function was chosen to make the blending smooth. 
`params_of_no_turning2` is roughly the radius within which Cassie stop turning, and `params_of_no_turning1` determines how fast the weight goes from 1 to 0. 
The use of logistic function could be overkill, I could've just used piecewise linear function...
___
*[examples/Cassie/run_osc_walking_controller.cc, line 135 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2cYnyA5sNIcNNwz3x:-MR3FaMGDHfAjAFlsP5U:bmwtt8k) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L135)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

We can move this to another class - not needed for this PR, but just worth noting in the future.
</blockquote></details>

I'm not familiar with Drake's `YamlReadArchive`, but according to the documentation shouldn't we have the method `Serialize()` inside struct `OSCWalkingGains`? 
___
*[examples/Cassie/osc/high_level_command.cc, line 119 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2dRgy31m_vuvmz8NG:-MR3I6As2FkPjw1jhSNm:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L119)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

move the negatives out of this class and into the gains
</blockquote></details>

done
___
*[examples/Cassie/osc/high_level_command.cc, line 167 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2daMtATSpM_tVcQIQ:-MR3IW5y33xFaE5WPIQU:bwvsqoc) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L167)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

why is there a negative here? I would expect `-vel_max_yaw_` to be smaller than `vel_max_yaw`
</blockquote></details>

Maybe it's a bad code style. I didn't want to create another variable called `vel_min_yaw`, because it's just negative `vel_max_yaw`. What this line of code is doing is clamping `des_yaw_vel` by a min and max value.
___
*[examples/Cassie/osc/high_level_command.cc, line 173 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2dxwN4v3XMdwpkSs6:-MR3JvAE4Sy-6GB4lVFL:breomnl) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L173)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

PR for another time, but I think we need to combine the global yaw tracking with the hip yaw tracking. Otherwise they will conflict with each other. Yukai's paper has a good method for how to select the desired hip yaw from the desired turning speed.
</blockquote></details>

There is currently no conflict in the controller. We are making `pelvis` to follow the desired global yaw angle, so OSC would use stance leg's hip yaw instead of swing leg's. But I see that Yukai divided the desired angle by 2 and directly track the hip yaw joint angles, which might be better than what we are doing now.

**Review by yangwill — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: all files reviewed, 4 unresolved discussions (waiting on @yminchen)

___
*[examples/Cassie/run_osc_walking_controller.cc, line 112 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2aCFa58HutzHObg4y:-MR5iC0m64W796A3U7yR:b-hotomt) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L112)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

How about rename them to `k_vel_ff_lateral` and `k_vel_fb_lateral`?
</blockquote></details>

do we need a feedforward term for raibert stepping? 
___
*[examples/Cassie/run_osc_walking_controller.cc, line 128 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2adN87dY-E0TrDh90:-MR5iPZjE5ozLcibrzwt:b-m92rcz) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L128)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

These two are a logistic function's parameters. I wanted Cassie to stop turning (tracking desired global yaw angle) once it's close enough to the target position. I blend the current yaw position and desired yaw position (this might not be the best choice), and the logistic function was chosen to make the blending smooth. 
`params_of_no_turning2` is roughly the radius within which Cassie stop turning, and `params_of_no_turning1` determines how fast the weight goes from 1 to 0. 
The use of logistic function could be overkill, I could've just used piecewise linear function...
</blockquote></details>

We can try just using standard linear interpolation to see if the logistic function is necessary. We should rename `params_of_no_turning2` to something like `yaw_deadband` 
___
*[examples/Cassie/run_osc_walking_controller.cc, line 135 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2cYnyA5sNIcNNwz3x:-MR5ikl_6V4GV7C9RfOw:buvls48) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L135)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I'm not familiar with Drake's `YamlReadArchive`, but according to the documentation shouldn't we have the method `Serialize()` inside struct `OSCWalkingGains`? 
</blockquote></details>

Yes we can move both into a separate class, see the jumping controller in the `invariant_impacts` branch for an example.
___
*[examples/Cassie/osc/high_level_command.cc, line 167 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2daMtATSpM_tVcQIQ:-MR5oPaw1eLOpxzrAPKA:bnoyv22) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L167)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Maybe it's a bad code style. I didn't want to create another variable called `vel_min_yaw`, because it's just negative `vel_max_yaw`. What this line of code is doing is clamping `des_yaw_vel` by a min and max value.
</blockquote></details>

I understand that but shouldn't `-vel_max_yaw` to be smaller than `vel_max_yaw` and not the other way around?

**Review by yminchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @yangwill)

___
*[examples/Cassie/run_osc_walking_controller.cc, line 112 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2aCFa58HutzHObg4y:-MR5qWNN4NH4TpwKmI5O:bhj0n8d) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L112)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

do we need a feedforward term for raibert stepping? 
</blockquote></details>

No we don't use the feedforward gains for raibert's but the capture point. I don't think I will be using the CP for walking. Maybe I can remove it in another PR?
___
*[examples/Cassie/run_osc_walking_controller.cc, line 128 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2adN87dY-E0TrDh90:-MR5rhIK4qkERXU49e53:bn8mxz9) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L128)):*
> We can try just using standard linear interpolation to see if the logistic function is necessary. We should rename params_of_no_turning2 to something like yaw_deadband
I'm renaming them to `yaw_deadband_radius` and `yaw_deadband_blur`. Let me know if you have better names!
___
*[examples/Cassie/run_osc_walking_controller.cc, line 135 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2cYnyA5sNIcNNwz3x:-MR5sk6C-yv_hHS_mtY5:b-64tar5) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/run_osc_walking_controller.cc#L135)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Yes we can move both into a separate class, see the jumping controller in the `invariant_impacts` branch for an example.
</blockquote></details>

I see what you are saying. I just moved it to a new header file.
___
*[examples/Cassie/osc/high_level_command.cc, line 167 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2daMtATSpM_tVcQIQ:-MR5tKnc77j2IMATkpiv:b-ht7oav) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L167)):*
> invariant_impacts
I think I'm missing something. `vel_max_yaw` is currently 0.5 which is positive, so yes `-vel_max_yaw` is smaller than `vel_max_yaw`. Not sure if I answered your question.

**Review by yangwill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/osc/high_level_command.cc, line 167 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2daMtATSpM_tVcQIQ:-MR6FMuN-8S7zt3Wsmq0:bl0w0i1) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L167)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> invariant_impacts
I think I'm missing something. `vel_max_yaw` is currently 0.5 which is positive, so yes `-vel_max_yaw` is smaller than `vel_max_yaw`. Not sure if I answered your question.
</blockquote></details>

Oh my mistakes, I misread the line of code. I thought it was a single function not both `std::min` and `std::max`. Maybe we should use `drake::math::saturate` (https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1math.html#adecdf6a7ef606861457807da4b56e7ff) instead.

**Review by yminchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @yangwill)

___
*[examples/Cassie/osc/high_level_command.cc, line 167 at r1](https://reviewable.io/reviews/dairlab/dairlib/224#-MR2daMtATSpM_tVcQIQ:-MR7-b1bBpqENfPuczuc:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/7d0ca16454a7ceaf37b193e43f0f9bdb4b88f30a/examples/Cassie/osc/high_level_command.cc#L167)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Oh my mistakes, I misread the line of code. I thought it was a single function not both `std::min` and `std::max`. Maybe we should use `drake::math::saturate` (https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1math.html#adecdf6a7ef606861457807da4b56e7ff) instead.
</blockquote></details>

Done.

**Review by yangwill — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/224)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
