### PR TITLE
remove raw pointers from options tracking data + fix drake Publish() deprecations

### PR DESCRIPTION
**Pull request by Brian-Acosta**
This change is [Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334)

### CODE REVIEW

**Review by yangwill — CHANGES_REQUESTED** [review]
Mostly :lgtm, small nitpick on naming PD gain multiplier and suggestion for modifying P vs D gains separately

> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334#-:-NM06WKuDB6_Rjy2MbRh:b-nedce2)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[`systems/controllers/osc/options_tracking_data.h` line 25 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/334#-NM05cvs6fBznkSpgIz0:-NM05cvs6fBznkSpgIz1:bhpv2z8) ([raw file](https://github.com/DAIRLab/dairlib/blob/cc95b4c6f234d00b0441e75a5bdefa03c1f1b9e9/systems/controllers/osc/options_tracking_data.h#L25)):*
> ```objc
>   // TOOD(yminchen): You can make ratio dictionary so that we have one ratio per
>   //  finite state
>   void SetTimeVaryingPDGains(
> ```

Since it's also a multiplier, can we rename it to `SetTimeVaryingPDGainMultiplier` for consistency?
___
*[`systems/controllers/osc/options_tracking_data.h` line 25 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/334#-NM06Mbn8GNx-fJdGbuG:-NM06Mbn8GNx-fJdGbuH:b7f6u0) ([raw file](https://github.com/DAIRLab/dairlib/blob/cc95b4c6f234d00b0441e75a5bdefa03c1f1b9e9/systems/controllers/osc/options_tracking_data.h#L25)):*
> ```objc
>   // TOOD(yminchen): You can make ratio dictionary so that we have one ratio per
>   //  finite state
>   void SetTimeVaryingPDGains(
> ```

Also looking at it now, i think it'd be beneficial to be able to set different gain multipliers for P vs D gains

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[`systems/controllers/osc/options_tracking_data.h` line 25 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/334#-NM05cvs6fBznkSpgIz0:-NM52sWSBjZ0A2phb0-f:b13pu5q) ([raw file](https://github.com/DAIRLab/dairlib/blob/cc95b4c6f234d00b0441e75a5bdefa03c1f1b9e9/systems/controllers/osc/options_tracking_data.h#L25)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Since it's also a multiplier, can we rename it to `SetTimeVaryingPDGainMultiplier` for consistency?
</blockquote></details>

Can do.
___
*[`systems/controllers/osc/options_tracking_data.h` line 25 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/334#-NM06Mbn8GNx-fJdGbuG:-NM52RVV1iHj7TptSGLQ:b-8div7b) ([raw file](https://github.com/DAIRLab/dairlib/blob/cc95b4c6f234d00b0441e75a5bdefa03c1f1b9e9/systems/controllers/osc/options_tracking_data.h#L25)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Also looking at it now, i think it'd be beneficial to be able to set different gain multipliers for P vs D gains
</blockquote></details>

Do you have a specific use case in mind? D gains are usually pretty low anyway. I don't mind doing it, just wondering if we have a use case before changing the API.

**Review by Brian-Acosta — COMMENTED** [review]
Name change done - see comment on separation

> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334#-:-NM5mbJZ7SJiw2wSXxQY:ba36sp4)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @yangwill and @yminchen)

**Review by yangwill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[`systems/controllers/osc/options_tracking_data.h` line 25 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/334#-NM06Mbn8GNx-fJdGbuG:-NM5osoO7Chqmow6KS1q:b-guebkh) ([raw file](https://github.com/DAIRLab/dairlib/blob/cc95b4c6f234d00b0441e75a5bdefa03c1f1b9e9/systems/controllers/osc/options_tracking_data.h#L25)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Do you have a specific use case in mind? D gains are usually pretty low anyway. I don't mind doing it, just wondering if we have a use case before changing the API.  
</blockquote></details>

Scaling P and D gains by the same scalar can cause a system that was previously critically damped to become under or over damped. In practice, I may want to scale my P gains by a large value but that may cause the D gains to pass the threshold where it starts to cause vibrations.

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[`systems/controllers/osc/options_tracking_data.h` line 25 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/334#-NM06Mbn8GNx-fJdGbuG:-NMFOcDK-A3xe7mRa3JF:b-896fjx) ([raw file](https://github.com/DAIRLab/dairlib/blob/cc95b4c6f234d00b0441e75a5bdefa03c1f1b9e9/systems/controllers/osc/options_tracking_data.h#L25)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Scaling P and D gains by the same scalar can cause a system that was previously critically damped to become under or over damped. In practice, I may want to scale my P gains by a large value but that may cause the D gains to pass the threshold where it starts to cause vibrations.
</blockquote></details>

Done

**Review by yangwill — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/334#-:-NMFQH-EEirniJlj-5se:bnfp4nl)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @yminchen)

**Pull request merged**
