### PR TITLE
Plotting refactor

### PR DESCRIPTION
**Pull request by Brian-Acosta**
Opening a pull request to get feedback on a hopefully easier to use and understand Cassie plotting script. 
I won't merge this until I've completely replicated the functionality of the current Cassie plotting script but it would be nice to get feedback ASAP

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268)

### CODE REVIEW

**Review by yangwill — COMMENTED** [review]
Nice - this already looks much much cleaner. 

> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268#-:-MoWSVClBdYskfUhB_PX:b-b4ydtp)* status: 1 of 13 files reviewed, all discussions resolved (waiting on @yminchen)

**Review by yminchen — COMMENTED** [review]
Looks clean and good! 

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268#-:-MoZDd9E4Eur4eHN0Y75:btcuwzx)* status: 1 of 13 files reviewed, all discussions resolved (waiting on @yangwill)

**Comment by Brian-Acosta** [comment]
You should now be able to use the YAML in bindings/pydairlib/analysis/plot_configs to set plotting options and replicate most of the plots we usually use

**Review by yangwill — CHANGES_REQUESTED** [review]
I'm testing the osc plotting functionality right now, and am getting size errors when trying to plot osc tracking datas that are not always active. It looks like `t_osc` is not guaranteed to be the same shape as the tracking data.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268#-:-MouEQwF-f5gpoMizgKY:bvgo6md)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @yangwill)

___
*[bindings/pydairlib/analysis/mbp_plotting_utils.py, line 232 at r5](https://reviewable.io/reviews/dairlab/dairlib/268#-MouEitfAuKIW2ZCJFd8:-MouEitfAuKIW2ZCJFd9:btsb7zx) ([raw file](https://github.com/dairlab/dairlib/blob/663a838671b4020677175b088d6ae330a2b222b5/bindings/pydairlib/analysis/mbp_plotting_utils.py#L232)):*
> ```Python
>     plotting_utils.make_plot(
>         data_dict,
>         't_osc',
> ```

issue I mentioned in my main comment errors out around here.

**Review by yangwill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[bindings/pydairlib/analysis/mbp_plotting_utils.py, line 259 at r5](https://reviewable.io/reviews/dairlab/dairlib/268#-MouI3VMDUOGxDO2MzdS:-MouI3VMDUOGxDO2MzdT:b-fx1mqz) ([raw file](https://github.com/dairlab/dairlib/blob/663a838671b4020677175b088d6ae330a2b222b5/bindings/pydairlib/analysis/mbp_plotting_utils.py#L259)):*
> ```Python
>         data['yddot_command_sol'] = tracking_data.yddot_command_sol[:, dim]
> 
>     return plot_general_osc_tracking_data(traj, deriv, dim, data,
> ```

i think `osc_debug['t_osc']` should be changed to `osc_debug['osc_debug_tracking_datas'][traj].t`

**Review by Brian-Acosta — COMMENTED** [review]
I just pushed a fix if you want to try it out again - my branch is still building

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268#-:-MouJD-ZAKhQBMNTS92B:b5ikesj)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

**Review by yangwill — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[bindings/pydairlib/analysis/osc_debug.py, line 61 at r6](https://reviewable.io/reviews/dairlab/dairlib/268#-MpDCDaP44gNewilRs9a:-MpDCDaP44gNewilRs9b:b-4uua5n) ([raw file](https://github.com/dairlab/dairlib/blob/96eb4e28b310cb623fa292e2db40d6e85f2371e4/bindings/pydairlib/analysis/osc_debug.py#L61)):*
> ```Python
> 
>         for name in self.tracking_costs:
>             if name not in tracking_cost_list:
> ```

bug/typo, I think it should be `if name not in tracking_data_list:`

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @yangwill)

___
*[bindings/pydairlib/analysis/mbp_plotting_utils.py, line 232 at r5](https://reviewable.io/reviews/dairlab/dairlib/268#-MouEitfAuKIW2ZCJFd8:-MpEV8d--MWtFPLVONoI:b58oi2n) ([raw file](https://github.com/dairlab/dairlib/blob/663a838671b4020677175b088d6ae330a2b222b5/bindings/pydairlib/analysis/mbp_plotting_utils.py#L232)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

issue I mentioned in my main comment errors out around here.
</blockquote></details>

should be fixed
___
*[bindings/pydairlib/analysis/mbp_plotting_utils.py, line 259 at r5](https://reviewable.io/reviews/dairlab/dairlib/268#-MouI3VMDUOGxDO2MzdS:-MpEV7Zy6135pdTcenOY:b58oi2n) ([raw file](https://github.com/dairlab/dairlib/blob/663a838671b4020677175b088d6ae330a2b222b5/bindings/pydairlib/analysis/mbp_plotting_utils.py#L259)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

i think `osc_debug['t_osc']` should be changed to `osc_debug['osc_debug_tracking_datas'][traj].t`
</blockquote></details>

should be fixed
___
*[bindings/pydairlib/analysis/osc_debug.py, line 61 at r6](https://reviewable.io/reviews/dairlab/dairlib/268#-MpDCDaP44gNewilRs9a:-MpEV4MzBImjxgH0yE1Y:b-7ql1td) ([raw file](https://github.com/dairlab/dairlib/blob/96eb4e28b310cb623fa292e2db40d6e85f2371e4/bindings/pydairlib/analysis/osc_debug.py#L61)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

bug/typo, I think it should be `if name not in tracking_data_list:`
</blockquote></details>

fixed

**Comment by Brian-Acosta** [comment]
This is ready to merge when you guys are satisfied

**Review by yminchen — APPROVED** [review]
Looks good to me

> Reviewed 2 of 12 files at r1, 2 of 9 files at r4, 3 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268#-:-Mr8K4MK4dSxuw16xmwX:b-owaf1x)* status: 7 of 17 files reviewed, 3 unresolved discussions (waiting on @yangwill and @yminchen)

**Review by yangwill — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/268#-:-MrA9sGnCn69svtmeHVL:bnfp4nl)* status: 7 of 17 files reviewed, all discussions resolved (waiting on @yangwill and @yminchen)

**Pull request merged**
