### PR TITLE
added low pass filtering for commanded height in standing controller

### PR DESCRIPTION
**Pull request by Brian-Acosta**
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/256)

### CODE REVIEW

**Review by yminchen — CHANGES_REQUESTED** [review]
Code looks good. Only minor comments. 
To make sure it's working as we expect, can we add a simple unit test? 

> Reviewed 3 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/256#-:-Mj-OG6o2S7et8Ae7TC6:b-7bbb08)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[systems/filtering/internal_lowpass_filter.h, line 12 at r3](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-MwgGE4C5eLky_aEh:-Mj-MwgGE4C5eLky_aEi:b-8li414) ([raw file](https://github.com/dairlab/dairlib/blob/9a59b0b83b437b0cd662a3602e87cd67f1dd5ab9/systems/filtering/internal_lowpass_filter.h#L12)):*
> ```objc
> class InternalLowpassFilter {
>  public:
>   InternalLowpassFilter(double tau, int n_states);
> ```

I think we can provide a second constructor which takes cutoff frequency instead of tau. 
After looking at your code, I believe the cutoff frequency is `1 / (2*pi*tau)`
___
*[systems/filtering/internal_lowpass_filter.cc, line 7 at r3](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-Jp3M063oMrlm16gU:-Mj-Jp3M063oMrlm16gV:bnvrx7n) ([raw file](https://github.com/dairlab/dairlib/blob/9a59b0b83b437b0cd662a3602e87cd67f1dd5ab9/systems/filtering/internal_lowpass_filter.cc#L7)):*
> ```cpp
> namespace dairlib {
> 
> InternalLowpassFilter::InternalLowpassFilter(double tau, int n_states) : tau_(tau) {
> ```

Maybe replace `n_states` with `n_y` to be consistent? 
___
*[systems/filtering/internal_lowpass_filter.cc, line 13 at r3](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-KETB7acq7GJIxw6A:-Mj-KETB7acq7GJIxw6B:b-lnf8yr) ([raw file](https://github.com/dairlab/dairlib/blob/9a59b0b83b437b0cd662a3602e87cd67f1dd5ab9/systems/filtering/internal_lowpass_filter.cc#L13)):*
> ```cpp
> 
> 
> VectorXd InternalLowpassFilter::filter(double timestamp, const VectorXd& x){
> ```

Maybe replace `x` with `y` to be consistent? 
___
*[systems/filtering/timestamped_lowpass_filter.h, line 19 at r3](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-KmFh-6qCBla0DRnt:-Mj-KmFh-6qCBla0DRnu:bdr79r) ([raw file](https://github.com/dairlab/dairlib/blob/9a59b0b83b437b0cd662a3602e87cd67f1dd5ab9/systems/filtering/timestamped_lowpass_filter.h#L19)):*
> ```objc
> class TimestampedLowpassFilter : public LeafSystem<double> {
>  public:
>   TimestampedLowpassFilter(double tau, int n_states);
> ```

Same comment about renaming `state` to `y`
___
*[systems/filtering/timestamped_lowpass_filter.cc, line 1 at r3](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-L0jj1RfOUnrhM7Cw:-Mj-L0jj1RfOUnrhM7Cx:bbvwqpj) ([raw file](https://github.com/dairlab/dairlib/blob/9a59b0b83b437b0cd662a3602e87cd67f1dd5ab9/systems/filtering/timestamped_lowpass_filter.cc#L1)):*
> ```
>   const TimestampedVector<double>* x_t = (TimestampedVector<double>*)this->EvalVectorInput(context, 0);
> ```
Some line's lengths exceed 80 characters. We can use Drake's tool to make the code style consistent

**Review by yangwill — CHANGES_REQUESTED** [review]
I agree with Yu Ming's comments, also added a few naming suggestions.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/256#-:-Mj-Wflr77xzkhKWI17G:bxvc22s)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[examples/Cassie/osc/BUILD.bazel, line 66 at r2](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-WZJF7sy4ujTQGBj0:-Mj-WZJF7sy4ujTQGBj1:b-enqtk4) ([raw file](https://github.com/dairlab/dairlib/blob/520614f676372b573a0f09699c5e8620cea80e9e/examples/Cassie/osc/BUILD.bazel#L66)):*
> ```Starlark
>         "//multibody:utils",
>         "//systems/controllers:control_utils",
>         "//systems/filtering:internal_lowpass_filter",
> ```

nitpick, change `filtering` to `filters` to have a consistent naming convention
___
*[systems/filtering/BUILD.bazel, line 5 at r2](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-WSkj4dteAmpF08XJ:-Mj-WSkj4dteAmpF08XK:b-25ak1y) ([raw file](https://github.com/dairlab/dairlib/blob/520614f676372b573a0f09699c5e8620cea80e9e/systems/filtering/BUILD.bazel#L5)):*
> ```Starlark
> cc_library(
>     name = "timestamped_lowpass_filter",
>     srcs = ["timestamped_lowpass_filter.cc"],
> ```

Nitpick, low pass should be two words to be consistent with Drake.
___
*[systems/filtering/BUILD.bazel, line 15 at r2](https://reviewable.io/reviews/dairlab/dairlib/256#-Mj-WTE_8QIPntdPvp9r:-Mj-WTE_8QIPntdPvp9s:b29mzh2) ([raw file](https://github.com/dairlab/dairlib/blob/520614f676372b573a0f09699c5e8620cea80e9e/systems/filtering/BUILD.bazel#L15)):*
> ```Starlark
> cc_library(
>     name = "internal_lowpass_filter",
>     srcs = ["internal_lowpass_filter.cc"],
> ```

change lowpass to two words here as well

**Comment by Brian-Acosta** [comment]
@yangwill Done. 
@yminchen formatting fixes done - I will write a unit test later - fwiw the filter works as expected inside the standing controller using the xbox controller in simulation. 

I can't include a second constructor since both constructors would take the same argument types (double, int) which is illegal in c++, though I can add static factory methods later if we really need them.

**Review by yminchen — COMMENTED** [review]
Yeah you are right. Maybe we can just document the conversion between cutoff frequency and the time constant 

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/256#-:-Mj-diXJAJBpnadcQxKU:b-e9gzd)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

**Pull request closed without merging**
