### PR TITLE
Alip default controller

### PR DESCRIPTION
**Pull request by Brian-Acosta**
Adds files to use the ALIP model (https://doi.org/10.1109/ICRA48506.2021.9560821) in the default walking controller.
Also updates the Cassie hardware PMD and logging infrastructure with quality of life improvements.

---
This change is [Reviewable](https://reviewable.io/reviews/dairlab/dairlib/280)

### CODE REVIEW

**Review by yminchen — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/280)* status: all files reviewed, 7 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[examples/Cassie/run_osc_walking_controller_alip.cc, line 284 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0U107-tm4XCD2w0MK:-Mv0U107-tm4XCD2w0ML:bahjt1v) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/examples/Cassie/run_osc_walking_controller_alip.cc#L284)):*
> ```cpp
>   // pelvis_traj_generator. Only the initial COM height is used in the x and y
>   // direction.
>   auto pelvis_traj_generator = builder.AddSystem<systems::ALIPTrajGenerator>(
> ```

Should we rename both `lipm_traj_generator` and `pelvis_traj_generator` so that it reflects it's based on angular momentum?



_Code quote:_
```cpp
pelvis_traj_gen
```
___
*[examples/Cassie/run_osc_walking_controller_alip.cc, line 510 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0P1gH4g8hm92Ux42o:-Mv0P1gH4g8hm92Ux42p:b-yig0jb) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/examples/Cassie/run_osc_walking_controller_alip.cc#L510)):*
> ```cpp
>   ComTrackingData center_of_mass_traj("lipm_traj", gains.K_p_com, gains.K_d_com,
>                                       gains.W_com, plant_w_spr, plant_w_spr);
>   center_of_mass_traj.AddFiniteStateToTrack(-1);
> ```

Is this saying we don't track the COM traj after the controller starts?



_Code quote:_
```cpp
center_of_mass_traj.AddFiniteStateToTrack
```
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 18 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0QGIqDSTHGoI_ojc4:-Mv0QGIqDSTHGoI_ojc5:bz5jj3n) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L18)):*
> ```objc
> /// The trajectory is a cubic spline (two segments of cubic polynomials).
> /// In the x-y plane, the start point of the traj is the swing foot position
> /// at lift-off, and the end point is either the capture point (CP) or the
> ```

Do we still use CP or neutral point in ALIP foot placement?



_Code quote (from systems/controllers/alip_swing_ft_traj_gen.cc):_
```cpp
m_ 
```
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 24 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0QTAf9P3q57Xt1VX1:-Mv0QTAf9P3q57Xt1VX2:bcbku9y) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L24)):*
> ```objc
> /// modified with two flags
> ///  - `add_speed_regularization`
> ///  - `is_feet_collision_avoid`
> ```

Some of the documentation here seems outdated.
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 45 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0Qa6x9GtDm8Xzsjn_:-Mv0Qa6x9GtDm8Xzsjna:b-qba6ux) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L45)):*
> ```objc
> /// - an integer indicates which foot step algorithm to use:
> ///     0 is the capture point
> ///     1 is the neutral point derived from LIPM given the stance duration
> ```

outdated documentation
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 49 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0Qd4v3dCLIMrtg5VJ:-Mv0Qd4v3dCLIMrtg5VK:biuupnq) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L49)):*
> ```objc
> class AlipSwingFootTrajGenerator : public drake::systems::LeafSystem<double> {
>  public:
>   // TODO(yminchen): clean up the parameters. Maybe we should extract the
> ```

Probably remove this since it's a different file now lol
___
*[systems/controllers/alip_swing_ft_traj_gen.cc, line 210 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0TEZr-FmaAyIOHLwk:-Mv0TEZr-FmaAyIOHLwl:b-iyhrec) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.cc#L210)):*
> ```cpp
>   Vector2d L_i;
> 
>   if (wrt_com_in_local_frame_) {
> ```

Question -- did you see if Cassie behaves differently when we toggle `wrt_com_in_local_frame_`?



_Code quote:_
```cpp
wrt_com_in_local_frame_
```

**Review by yminchen — COMMENTED** [review]
Oops, the "CODE QUOTE"'s in my comments were all unintentional. Please ignore them

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/280#-:-Mv0Vl6t3uOIRnqSA3_m:b-gwn8d5)* status: all files reviewed, 7 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

**Review by Brian-Acosta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/280)* status: all files reviewed, 7 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/run_osc_walking_controller_alip.cc, line 284 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0U107-tm4XCD2w0MK:-Mv4_qx35J7v-6praLzf:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/examples/Cassie/run_osc_walking_controller_alip.cc#L284)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Should we rename both `lipm_traj_generator` and `pelvis_traj_generator` so that it reflects it's based on angular momentum?
</blockquote></details>

Done
___
*[examples/Cassie/run_osc_walking_controller_alip.cc, line 510 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0P1gH4g8hm92Ux42o:-Mv4ZIII5_aO-oWwL84X:b-uaxy4l) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/examples/Cassie/run_osc_walking_controller_alip.cc#L510)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Is this saying we don't track the COM traj after the controller starts?
</blockquote></details>

This says that the tracking data is always active
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 18 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0QGIqDSTHGoI_ojc4:-Mv4cVXs8zf7Ee2MLsDT:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L18)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Do we still use CP or neutral point in ALIP foot placement?
</blockquote></details>

Done
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 24 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0QTAf9P3q57Xt1VX1:-Mv4cWAR9LJC1D3LEZIo:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L24)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Some of the documentation here seems outdated.
</blockquote></details>

Done
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 45 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0Qa6x9GtDm8Xzsjn_:-Mv4cYEpBj6MDTkuDyue:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L45)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

outdated documentation
</blockquote></details>

Done
___
*[systems/controllers/alip_swing_ft_traj_gen.h, line 49 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0Qd4v3dCLIMrtg5VJ:-Mv4c_bxA71V9FX-NAaF:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.h#L49)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Probably remove this since it's a different file now lol
</blockquote></details>

Done
___
*[systems/controllers/alip_swing_ft_traj_gen.cc, line 210 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0TEZr-FmaAyIOHLwk:-Mv4tFhI9z_QKSznYFJJ:br1dfn4) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/systems/controllers/alip_swing_ft_traj_gen.cc#L210)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Question -- did you see if Cassie behaves differently when we toggle `wrt_com_in_local_frame_`?
</blockquote></details>

just checked this and it doesn't work well without relative foot placement. I got rid of this option since we only ever use relative foot placement in practice

**Review by yminchen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/280)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @yangwill, and @yminchen)

___
*[examples/Cassie/run_osc_walking_controller_alip.cc, line 510 at r1](https://reviewable.io/reviews/dairlab/dairlib/280#-Mv0P1gH4g8hm92Ux42o:-MvXKoO6Er0LmA3WseYP:b-7ym9rf) ([raw file](https://github.com/dairlab/dairlib/blob/1c86dfdd37e01c1791f9b10f9ed25d1700d0e884/examples/Cassie/run_osc_walking_controller_alip.cc#L510)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

This says that the tracking data is always active
</blockquote></details>

Oh, looks like this is what we have to do with the new OscTrackingData? I remember TrackngData that I implemented assume it's always active if no state was added

**Review by yminchen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/280#-:-MvcVszx2YdLYxEuV2OD:bnfp4nl)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta, @yangwill, and @yminchen)

**Pull request merged**
