### PR TITLE
Fix a bug and improve dircon squatting script 

### PR DESCRIPTION
**Pull request by yminchen**
Fix scaling bugs, rename a variable, use bounding box constraint, scale the cost and provide initial guesses for slack/time variables

### CODE REVIEW

**Comment by yminchen** [comment]
> What's the effect on benchmark runtime, if any?

Here is what I observed about the solve time:
* Fixing the constraint scaling bug: solve time barely changed
* Using bounding box constraints: slightly decreased
* Scaling the cost: increased by ~50%
* Providing initial guesses for the slack and time variables: decreased by 50~100%

I am not sure why scaling the cost didn't help to improve the solve time in this example

**Comment by mposa** [comment]
> * Scaling the cost: increased by ~50%
So why scale the cost in this PR?

> * Providing initial guesses for the slack and time variables: decreased by 50~100%
100% reduction = instantaneous?

**Comment by yminchen** [comment]
Ah I made some mistakes in the previous comment. I benchmarked solve time more carefully this time and here is the result: 
* Fixing the constraint scaling bug: increased by ~60 seconds
* Using bounding box constraints: decreased slightly
* Providing initial guesses for the slack and time variables: decreased by ~10 seconds
* Scaling the cost: reduced by ~50 seconds
The above changes is listed in order. With a different order, we might get a different solve time result.

Interestingly, the unintentional bug increased the solving speed

**Comment by mposa** [comment]
1/500 is a pretty big scale factor to include if it doesn't actually improve performance. Might be worth dialing it back to see what happens.

**Comment by yminchen** [comment]
Ok, I'll close this PR for now

**Pull request closed without merging**
